### ISSUE TITLE
Add OpenSSH 8 recommendations

### ISSUE THREAD

**Issue by immanuelfodor** [jtesta/ssh-audit#1]
Hi Joe, 

The tool currently suggests recommended settings for OpenSSH 7.6 but I currently have `OpenSSH_8.0p1, OpenSSL 1.1.1c 28 May 2019`, so it would be great to have up-to-date kex/mac/etc recommendations what to enable, disable, and so on. There might be such in the official docs but the tool should make it easy to find them via its output.

```
# algorithm recommendations (for OpenSSH 7.6)
...
```

**Comment by jtesta** [comment]
@immanuelfodor I just pushed an update to the master branch.  Can you give it a test against your v8.0 instance?  Thanks!

**Comment by immanuelfodor** [comment]
Nice work, looks good, you were very quick with the update! 

It might be just one guy's opinion but what do you think about this? I followed this guide since published: 

https://stribika.github.io/2015/01/04/secure-secure-shell.html

> Recommended /etc/ssh/sshd_config snippet:

> `MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com`

> Encrypt-then-MAC: I am not aware of a security proof for CTR-and-HMAC but I also don’t think CTR decryption can fail. Since there are no downgrade attacks, you can add them to the end of the list. You can also do this on a host by host basis so you know which ones are less safe.

Change log at the bottom:

> I’m now allowing Encrypt-and-MAC algorithms with CTR ciphers as a last resort. I initially thought it was possible to use downgrade attacks, I now think it is not.

The audit tool can't determine the MACs order in the config, this is why these are marked for removal? Do you have some counter-proof that these should be not allowed these day's? I'm just interested in the best config :grinning: 

```
(rec) -hmac-sha2-256                        -- mac algorithm to remove         
(rec) -hmac-sha2-512                        -- mac algorithm to remove         
(rec) -umac-128@openssh.com                 -- mac algorithm to remove
```

**Comment by jtesta** [comment]
> I followed this guide since published: https://stribika.github.io/2015/01/04/secure-secure-shell.html

That's funny, because that exact same guide is what got me into this SSH hardening topic years ago!  It hasn't been updated in a while, though, so I made my own based on it here: https://www.sshaudit.com/hardening_guides.html.

The Encrypt-and-MAC design introduced much more attack surface (see DJM's blog post about it here; he's the OpenSSH maintainer: http://blog.djm.net.au/2013/11/chacha20-and-poly1305-in-openssh.html).  Encrypt-then-MAC (ETM) doesn't have these problems, but they introduce another issue: the plaintext packet lengths are exposed.  So the question is: is it better to use the EAM algorithms with their problems, or ETM and get a higher risk of traffic analysis?  Generally, it seems people are leaning towards ETM being a little bit better.

```
(rec) -hmac-sha2-256                        -- mac algorithm to remove         
(rec) -hmac-sha2-512                        -- mac algorithm to remove         
(rec) -umac-128@openssh.com                 -- mac algorithm to remove
```

The above algorithms are flagged as warnings (not failures), because they use the EAM method instead of ETM.  The tool recommends that all algorithms that have at least warnings be removed.  I didn't change this behavior; that's how it worked before.

**Comment by immanuelfodor** [comment]
Thanks for the detailed explanation, now I have better understanding of this and hardened further my config thanks to your guidance! :) I think we can close this issue now.

**Comment by immanuelfodor** [comment]
Please let me one further question I just came to: why is that your guide doesn't include the below 3 kex algorithms while the tool recommends them? Are there some caveats using them in some circumstances, and so being [optionally recommended](https://tools.ietf.org/id/draft-baushke-ssh-dh-group-sha2-02.xml#n-key-exchange-algorithms) doesn't add value?

```
(rec) +diffie-hellman-group14-sha256        -- kex algorithm to append 
(rec) +diffie-hellman-group16-sha512        -- kex algorithm to append 
(rec) +diffie-hellman-group18-sha512        -- kex algorithm to append
```

**Comment by immanuelfodor** [comment]
According to https://www.openssh.com/txt/release-5.7 the order of kex algorithms matter:

 > * ssh(1)/sshd(8): add a KexAlgorithms knob to the client and server
>    configuration to allow selection of which key exchange methods are
>    used by ssh(1) and sshd(8) and their order of preference.

In this case where would you put these in the recommended line? 

`KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256`

`25519, 25519@, group18, group16, dhge` maybe? 

From what you said, I have a feeling that dhge would result in a warning in the future as I think it's also 2048-bits but [well supported](https://ssh-comparison.quendi.de/comparison/kex.html), so for compatibility's sake, it should go to the end or be removed when we follow >2048 strictly. Or if I only kept >=3071 moduli, then it's fine? Is it like a parameterized-by-moduli algorithm to put it in this way? Dhge is a bit of a black box for me to be honest :)

**Comment by immanuelfodor** [comment]
Well, thank you for everything, this was one of the best and most interesting Github conversations for me. These additional bits of information, opinions and suggestions would worth a blog post to let others know about it, too, if you are going to update your guide, you could use it to enrich it. Thanks again!

**Comment by immanuelfodor** [comment]
Wow, bookmarked it!
