### ISSUE TITLE
Add a Table of Contents (ToC) to README.md

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#100]
The `README.md` is becoming very long, this presents two problems:
  1. New users can't see at a glance what sort of information it contains without scrolling through the entire thing.
  2. It's difficult to quickly jump to a specific section of the page.

A Table of Contents (ToC) would help address the above. For an example of what I mean, see the [VimWiki](https://github.com/vimwiki/vimwiki) project's `README.md`.

I don't know if GitHub provides any way to automate the generation of a ToC or whether this would have to be updated manually.

What do you think of this idea?

**Comment by thecliguy** [comment]
If you're happy for me to add a manually generated ToC (which I think will be fine), let me know and I'll submit a PR. This will take me no time at all to produce.

**Comment by jtesta** [comment]
> If you're happy for me to add a manually generated ToC (which I think
> will be fine), let me know and I'll submit a PR.

Sure, that would be helpful!  I was thinking lately, too, that the
README is getting unwieldy...

**Comment by thecliguy** [comment]
PR submitted, see #101.

**Comment by jtesta** [comment]
Merged.  Thanks!
