### ISSUE TITLE
Group Size Enumeration of diffie-hellman-group-exchange-sha1 and diffie-hellman-group-exchange-sha256

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#109]
I've encountered an SSH server where the Diffie-Hellman group size used by the key exchange algorithm `diffie-hellman-group-exchange-sha256` is hardcoded and cannot be seen or configured by an administrator.

My plan was to use ssh-audit to scan the server and find out more information about the supported group size(s) but then I realised that ssh-audit only returns the minimum value.

I studied [RFC 4419](https://datatracker.ietf.org/doc/html/rfc4419) which explains how the client requests a modulus from the server by specifying a minimum, a preferred and a maximum value (expressed in bits). The `send_init_gex` function in ssh-audit has been implemented as per the explanation in RFC 4419, it accepts `minbits`, `prefbits` and `maxbits`.

I was able to modify `gextest.py` to invoke `send_init_gex` with `minbits`, `prefbits` and `maxbits` of the same value from 0 to 8192. This gave me the answer I was looking for, it showed that the server was configured with group sizes of 1024, 2048, 3072, 4096 and 6144. Using this information I can now contact the manufacturer of the SSH server software and ask if they will consider removing 1024.

@jtesta What do you think about about adding group size enumeration as a feature to ssh-audit? I could submit my patch as a draft for you to review?

Enumerating every value from 0 to 8192 is a slow process because it has to make a new connection to the target server each time. In my case this was not a problem because I ran the patched version of ssh-audit on the SSH server itself. However, if someone were to attempt this over a network it may cause a firewall's rate control to be triggered resulting in requests being blocked. So we'd probably need to mention this as a potential caveat in the documentation.

**Comment by jtesta** [comment]
Sure, how about a non-default option that lets the user do a scan?
 You're right that this causes a huge slow-down in scan times, which is
why I'd want it to be non-default.

What strategy would it use?  Only round numbers like 1024, 2048, etc?
 Something else?

**Comment by thecliguy** [comment]
Originally I tried using increments of 1024 _(1024, 2048, 3072...)_. 

I then switched to increments of 1 _(1, 2, 3...)_ and although this was slow it did reveal that an Ubuntu 20.04 server I scanned was using group sizes that didn't follow an exact pattern: 2048, 3072, 4096, **6144**, **7680**, 8192. I wouldn't have found this out using increments of 1024.

So perhaps we could give the user the option to specify a `Start Value` an `Increment Value` and an `End Value`... And if the user doesn't provide any values then perhaps we can agree on some sensible defaults.

What do you think?

**Comment by jtesta** [comment]
Sure, that works.

**Comment by thecliguy** [comment]
@jtesta What do you think of this as a parameter? Is the name OK, or too cryptic?

```
-D,  --dh-group-size=<start,stop,step>
```

I've used the same parameter value names as Python's [range()](https://www.w3schools.com/python/ref_func_range.asp) function.

I'll come up with some suitable help text to accompany the parameter.

Please let me know if you have a better idea, I'm open to any feedback...

**Comment by jtesta** [comment]
It's a GEX test, so how about -G / --gex-test ?

**Comment by thecliguy** [comment]
> 
> It's a GEX test, so how about -G / --gex-test ?

Perfect - but why an uppercase `G`? I thought the convention was to assign lowercase letters before uppercase.

**Comment by jtesta** [comment]
Ok, lowercase 'g' it is!

**Comment by thecliguy** [comment]
Sorry, it's still my intention to work on implementing this feature. Life has just been a bit busy lately.

**Comment by thecliguy** [comment]
@jtesta Sorry for leaving this hanging for a ridiculously long time...

I've implemented `-g / --gex-test` to accept two types of input:

1. **Range Syntax:** `--gex-test=<bit_start;bit_end;bit_step>`  
    Example - Scan from 0 bit to 5120 bit at increments of 1024 bit: `--gex-test=0;5120;1024`

    (**NB:** If `bit_start` is less than `bit_end` then the sequence is in descending order, EG: `--gex-test=50;0;5` would scan for 50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0.)

2. **List Syntax:** `--gex-test=<n,n,...>`
    Example - Scan for 120 bit, 1024 bit, 3072 bit and 5000 bit: `--gex-test=120,1024,3072,5000`

The only problem I've encountered is with the Range Syntax... When Bash sees a semicolon (`;`), it's treated as a command separator. To suppress this behaviour you have to wrap the value in quotes, EG: `--gex-test="0;5120;1024"`. Do you think it's acceptable to live with this, or should I use a different delimiter for ranges? If you think it's best to use a different delimiter, do you have any suggestion what to use instead of a semicolon?

Please do let me know if you have any other comments or suggestions before I continue writing this code...

**Comment by thecliguy** [comment]
@jtesta Hi Joe, hope you're well. I've gone ahead and implemented the new parameters `-g/--gex-test=` to test for Diffie-Hellman Group Exchange modulus size against a target server.

Please can you review my PR under #131 and provide feedback.

**Comment by thecliguy** [comment]
@jtesta Just wondered if you'd had a chance to review #131? 

There's some other issues I'd like to work on but I'd prefer to wait until #131 has been merged, if you're happy to accept it that is...

**Comment by jtesta** [comment]
Yep, everything is going well here!  How about you?

I've fallen a bit behind on looking at PRs and issues, but I have some
free time this weekend that I'll put towards it.  Thanks for the ping!

**Comment by thecliguy** [comment]
Everything good here thanks.

Thank you, that would be great.

On 24 February 2022 19:12:07 GMT+00:00, Joe Testa ***@***.***> wrote:
>Yep, everything is going well here!  How about you?
>
>I've fallen a bit behind on looking at PRs and issues, but I have some
>free time this weekend that I'll put towards it.  Thanks for the ping!
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/jtesta/ssh-audit/issues/109#issuecomment-1050173354
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jtesta** [comment]
I applied the PR to branch "pr131" in order to fix the pylint errors,
consolidate the error checking, and make some other small fixes.  Can
you give this branch a test and see if it works?  If so, I'll merge it
into the master branch.

**Comment by egberts** [comment]
Ummm.  About that uppercase option, I was racking my mind about the potential (but wider) use of the lowercase g option.  

I do do lots of code reviews and unit tests on OpenSSH.  

At the moment, closest lowercase g (and better?) candidate seems to be GSSAPI and grouping of `AuthenticationMethods`, neither are network-based analysis that ssh-audit focus on.  

Should be good for using that lowercase g.

**Comment by thecliguy** [comment]
> I applied the PR to branch "pr131" in order to fix the pylint errors, consolidate the error checking, and make some other small fixes. Can you give this branch a test and see if it works? If so, I'll merge it into the master branch.

@jtesta Thanks very much, I'll do some testing against that branch later today and will get back to you with any feedback...

**Comment by thecliguy** [comment]
@jtesta Sorry for the delay, I've now tested the branch "pr131".

Please can you make one minor change...

The following in the man page should be changed from `<n[,n,...]>` to `<x[,y,...]>`:

https://github.com/jtesta/ssh-audit/blob/d59cabe48489c1f40049b7c4b9ceaad1a57e9724/ssh-audit.1#L65

Other than that, it all looks good to me. Thanks for reviewing the PR, much appreciated.

**Comment by thecliguy** [comment]
@jtesta Are you happy to merge "pr131" just with that one minor change to the man page that I mentioned in my last comment?

**Comment by jtesta** [comment]
Yep, I'll be merging that soon!

**Comment by thecliguy** [comment]
Fantastic, thank you 👍

**Comment by thecliguy** [comment]
@jtesta Thanks for merging. 

Should the Usage section of `README.md` be updated to include `-g` and `--gex-test`? Or do you only update this once a new release has been made?

**Comment by jtesta** [comment]
Yes, that should be updated too.  I usually do that as soon as a new
feature is added, but I overlooked that this time.

**Comment by thecliguy** [comment]
@jtesta I've updated the `README.md`, see #135. 

Please can you merge when you get time and then this issue can be closed.

**Comment by thecliguy** [comment]
Thanks for updating the README with #135.

**Comment by jtesta** [comment]
> Thanks for updating the README with #135.

Thanks again for all your work!
