### ISSUE TITLE
Inconsistency with rsa-sha2-512/256 on Hardened policies

### ISSUE THREAD

**Issue by Keisial** [jtesta/ssh-audit#110]
Hardened policies for OpenSSH Server >= v8.2 say that the server MUST support rsa-sha2-512 and rsa-sha2-256, but poicies for < v8.2 say it MUST NOT support either of them.

This is inconsistent, since if it's suitable in OpenSSH 8.2, it should be good to use as well on v8.1 (unless its implementation was broken, or something like that, which doesn't seem to be the case). ssh-audit itself notes these were added in v7.2, so they _can_ be used. Maybe it's related to the problem noted in Issue #28, where in some versions it's impossible to disable only rsa-sha while it works in others. This is an argument for not requiring it, but not for requiring its absence, specially since there are platforms where it works. If the server is unable to disable only that one, it would already fail the rsa-sha check.

I think the solution would be to add 'rsa-sha2-512', 'rsa-sha2-256' to optional_host_keys on earlier versions. But if there is a reason these must not be used there, then it lacks documentation explaining it.

**Comment by jtesta** [comment]
Thanks for pointing this out!  I verified that OpenSSH 8.1 does indeed have the ability to restrict on `rsa-sha2-512` and `rsa-sha2-256`.  I updated the built-in policies in https://github.com/jtesta/ssh-audit/commit/45da9f20ae318274aa4bcf628eaec9f6765c9b0f to reflect this.

Thanks again!

**Comment by Keisial** [comment]
Great, thanks!

And for the tool itself as well, of course. :)
