### ISSUE TITLE
Where can I find list of available options for auditing policies?

### ISSUE THREAD

**Issue by TafkaMax** [jtesta/ssh-audit#112]
Please add that to the documentation. I want to see if servers match this configuration.
```
HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
PasswordAuthentication no
ChallengeResponseAuthentication no
PermitRootLogin without-password
```

**Comment by jtesta** [comment]
> I want to see if servers match this configuration.

Assuming your config isn't standard, you can create a custom policy
using a server config as a template with '-M'.  Then you can manually
edit the resulting file as necessary.  The format of the custom policy
file isn't documented, but it should be easy enough to follow along.

> PasswordAuthentication no
> ChallengeResponseAuthentication no
> PermitRootLogin without-password

These aren't properties that ssh-audit can examine, as they would
require doing a full SSH handshake.

**Comment by TafkaMax** [comment]
Ah okay. My bad. I didn't know the whole details of this program. I already tried the -M option and it worked nicely and if those are all the options there, then it is documented. I was just thinking if I could also verify the other properties... Will close it, thanks!

**Comment by jtesta** [comment]
Sure thing!
