### ISSUE TITLE
After applying steps in hardening guide in Centos 7, ssh-audit still fails

### ISSUE THREAD

**Issue by AlexDaciuk** [jtesta/ssh-audit#119]
Hi, 

Im using ssh-audit to check our ssh config in different linux instances across our AWS infrastructure

ssh-audit : docker image positronsecurity/ssh-audit:latest
OS involved : Centos 7
ssh-server version : 7.4p1-21.el7

My sshd_config ends up with 

```
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
```

But after running ssh-audit I get

```
# algorithm recommendations (for OpenSSH 7.4)
(rec) -ssh-rsa                              -- key algorithm to remove
(rec) +diffie-hellman-group14-sha256        -- kex algorithm to append
```

And it exits with code 3

I don't see any KeyAlgorithm in my sshd_config that has **rsa** in it, is the hardening guide out of date? or ssh-audit needs to take the OpenSSH package of Centos 7 into account?

Thanks
Alex

**Comment by jtesta** [comment]
Hi Alex.  Looks like the hardening guide needed some updating, which I just performed.  Namely, the OpenSSH version shipped with CentOS 7 does not support SHA2 hashes for RSA keys, hence RSA keys must be disabled entirely.

To fix this on your end, you can run the following 5 commands on your servers:
```
sed -i '/ssh_host_rsa_key/d' /usr/lib/systemd/system/sshd-keygen.service  # Don't auto regenerate RSA keys.
sed -i '/ssh_host_ecdsa_key/d' /usr/lib/systemd/system/sshd-keygen.service  # Don't auto regenerate ECDSA keys.
systemctl daemon-reload  # Tell systemd that we modified the above file.

sed -i 's/^HostKey \/etc\/ssh\/ssh_host_\(rsa\|dsa\|ecdsa\)_key$/\#HostKey \/etc\/ssh\/ssh_host_\1_key/g' /etc/ssh/sshd_config  # Comment out any HostKey lines that reference RSA, DSA, or ECDSA.
rm -f /etc/ssh/ssh_host_rsa_key* /etc/ssh/ssh_host_ecdsa_key*  # Delete any RSA and ECDSA keys.
```

Moving forward, the updated CentOS 7 guide will properly disable RSA keys.

Thanks for reporting!
