### ISSUE TITLE
JSON output does not have a recommendations section

### ISSUE THREAD

**Issue by VeNoMouS** [jtesta/ssh-audit#122]
looking at your code, you don't output it in your `build_struct` function...

**Comment by VeNoMouS** [comment]
Since no response... a hack can be done along the lines ..

```python
def build_struct(
    target_host: str,
    banner: Optional['Banner'],
    kex: Optional['SSH2_Kex'] = None,
    pkm: Optional['SSH1_PublicKeyMessage'] = None,
    client_host: Optional[str] = None,
    software=None,
    algs=None
) -> Any:

    .....

    software, alg_rec = algs.get_recommendations(software, True)
    res['recommendations'] = {
        'critical': {},
        'warning': {}
    }
    
    for alg_type in ['kex', 'key', 'enc', 'mac']:
        if alg_type in alg_rec[2]:
            for action in ['del', 'add', 'chg']:
                if action in alg_rec[2][alg_type]:
                    for n in alg_rec[2][alg_type][action]:
                        level = 'critical' if alg_rec[2][alg_type][action][n] >= 10 else 'warning'

                        if action not in res['recommendations'][level]:
                            res['recommendations'][level][action] = {}
                            
                        if alg_type not in res['recommendations'][level][action]:
                            res['recommendations'][level][action][alg_type] = []
                        
                        res['recommendations'][level][action][alg_type].append(n)
    
    return res
```
....

```python3
def output(out: OutputBuffer, aconf: AuditConf, banner: Optional[Banner], header: List[str], client_host: Optional[str] = None, kex: Optional[SSH2_Kex] = None, pkm: Optional[SSH1_PublicKeyMessage] = None, print_target: bool = False) -> int:
    ......
    if aconf.json:
        out.reset()
        # Build & write the JSON struct.
        out.info(
            json.dumps(
                build_struct(
                    aconf.host,
                    banner,
                    kex=kex,
                    client_host=client_host,
                    software=software,
                    algs=algs
                ),
                indent=4 if aconf.json_print_indent else None, sort_keys=True
            )
        )
```
        
honestly , reading your code is a nightmare, if you're reformatting everything so much all over the place, change it at the source and structure it accordingly so you're not having to loop on everything in order to format it... 

just my 2 cents.

**Comment by VeNoMouS** [comment]
Additionally, since you don't output in a logical structured manner to an object or structured dict as stated above, it makes it impossible / impractical using this as 3rd party python module ... as the end developer has to manually restructure everything your doing just to get logical output.

**Comment by jtesta** [comment]
> honestly , reading your code is a nightmare

I didn't write those parts, but I am responsible for maintaining them.
 I'll gladly accept a PR to fix it though!

As for the issue at hand, it seems like you did most of the work
already.  A PR would speed things up, if you're able to make one.
 Thanks!

**Comment by mr-pmillz** [comment]
Hey @VeNoMouS  @jtesta  @letiemble 

I've implemented @VeNoMouS 's changes 
I also added the corresponding CVE results to the JSON output in a structured manner as well.
Tested and appears to work.

Let me know what you think @jtesta 
Cheers 🍻

**Comment by Thibaut833** [comment]
Hi,

@jtesta can you accept this pull request please ? I want to use the json format with recommendations.

Thanks a lot.

Best regards.

**Comment by jtesta** [comment]
@VeNoMouS : I just committed a patch to add recommendations and CVE information to the JSON output.  Please give it a try!

CC: @Thibaut833
