### ISSUE TITLE
offline analysis?

### ISSUE THREAD

**Issue by egberts** [jtesta/ssh-audit#129]
It is too bad that we don’t have any offline analysis on `sshd_config` file

I would like to warn admins of badly formed `AuthenticationMethods` such as:

    password,pubkey # reverse these
    pubkey password  # missing comma

**Comment by egberts** [comment]
I am reminded of this snippet:

https://serverfault.com/a/996992/250390

**Comment by jtesta** [comment]
That would be useful, but outside the scope of this project.
