### ISSUE TITLE
Aruba AOS-S 16.11 hardening guide added to the Wiki

### ISSUE THREAD

**Issue by matsimon** [jtesta/ssh-audit#137]
Thank you for ssh-audit, it has been a helpful tool for me so far!

I've added a hardening guide for Aruba's ArubaOS Switch (AOS-S) 16.11 to the wiki, while trying to remain close to the style of the guide on ssh-audit.com. I've not yet added a link to the main page of the hardening guide, if there are any objections, please let me know.

**Comment by matsimon** [comment]
Here is the direct link:
https://github.com/jtesta/ssh-audit/wiki/ArubaOS-Switch-(AOS-S)-16.11

**Comment by jtesta** [comment]
This has been added to the list of community-provided hardening guides: https://www.ssh-audit.com/hardening_guides.html

Thanks for contributing!
