### ISSUE TITLE
Server encryption aes256-cbc is black in web client, red in local client

### ISSUE THREAD

**Issue by severach** [jtesta/ssh-audit#139]
All CBC should be red and have the CBC note, including CBC that are red for other reasons.

Server `hmac-sha2-256-etm@openssh.com` is black in the web client and green in the local client. Some MACs like etm should be green in the webclient unless you're suggesting we all switch to -gcm and eliminate the separate MAC.

~~Server `diffie-hellman-group-exchange-sha256 (1024-bit)` is red. Client `diffie-hellman-group-exchange-sha256` is black. Aren't they the same?~~ The server chooses the size.

`diffie-hellman-group-exchange-sha256 (4096-bit)` is colored green. `diffie-hellman-group16-sha512` with the same 4096 MODP is colored black. They look the same to me.

**Comment by jtesta** [comment]
The web application has been updated to flag all CBC-based ciphers.  Thanks for contributing!
