### ISSUE TITLE
SSH comparison chart (reference)

### ISSUE THREAD

**Issue by egberts** [jtesta/ssh-audit#141]
Just leaving this SSH comparison chart here in case some documentation page comes along to soak this up. 

https://ssh-comparison.quendi.de/comparison/cipher.html

**Comment by manfred-kaiser** [comment]
Thanks for the comparison. Great work :+1:

**Comment by jtesta** [comment]
@egberts : Thanks for posting this.  I added this link to the project's wiki.  I think that's a good long-term home for it rather than as an issue.  Thanks again!
