### ISSUE TITLE
Unknown Algorithm: hmac-sha1-96@openssh.com

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#148]
Hi @jtesta 

I ran an ssh-audit client scan against [Cyberduck](https://cyberduck.io/) version 8.4.4 (38366) on Windows and it reported an unknown algorithm:

```
!!! WARNING: unknown algorithm(s) found!: hmac-sha1-96@openssh.com.  Please email the full output above to the maintainer (jtesta@positronsecurity.com), or create a Github issue at <https://github.com/jtesta/ssh-audit/issues>.
```

The algorithm `hmac-sha1-96` is present in `ssh2_kexdb.py` but not this `@openssh.com` specific implementation of it. 

Something that occurred to me is whether `hmac-sha1-96@openssh.com` really exists or not... So I searched the [OpenSSH Specifications](https://www.openssh.com/specs.html), the [OpenSSH source code for BSD](https://www.openssh.com/ftp.html), the [OpenSSH portable release source code](https://github.com/openssh/openssh-portable) and then a whole bunch of other places... And I found absolutely nothing. Nothing that I would consider to be canonical evidence of this algorithm having been implemented.

It's definitely possible that I've missed something... It's not really like I know my way around the OpenSSH source code. 

If `hmac-sha1-96@openssh.com` does indeed exist, do you know where its existence would be documented?

**Comment by egberts** [comment]
It is a Cisco thing.  Was created to deal with existing (but broken) IPSec used within Cisco products. 

https://community.cisco.com/t5/other-security-subjects/difference-between-mac-algorithms-hmac-sha1-and-hmac-sha1-96/td-p/4046166

**Comment by jtesta** [comment]
Thanks for reporting this, @thecliguy !  I've committed this to master.
