### ISSUE TITLE
Reformat the Usage Text for --gex-test

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#151]
The usage text in `ssh_audit.py` was neatly arranged so it doesn't exceed 80 characters... However `--gex-test` now breaks this convention:

```
   -g,  --gex-test=<x[,y,...] | min:pref:max[,min:pref:max,...] | x-y[:step]>  dh gex modulus size test
```

Also (a minor point), `min:pref:max[,min:pref:max,...]` should be `min1:pref1:max1[,min2:pref2:max2,...]` to be consistent with the man page. But this change with the existing formatting would make the line even longer (by an extra six characters).

@jtesta What do you think if we reformat the text as follows?:

```
   -g,  --gex-test=<x[,y,...]>  dh gex mod size test
                   <min1:pref1:max1[,min2:pref2:max2,...]>
                   <x-y[:step]>
```

**Comment by jtesta** [comment]
Yep, sounds good!

**Comment by thecliguy** [comment]
PR submitted, see #158.

**Comment by jtesta** [comment]
Merged in https://github.com/jtesta/ssh-audit/commit/e50ac5c84d46e902e026babd22b5f3b4465fa93c via #158.
