### ISSUE TITLE
Usage Output Doesn't Respect -n/--no-colors

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#153]
A very minor issue...

The output produced by `usage` doesn't respect `-n`/`--no-colors`.

Should be an easy fix.

**Comment by jtesta** [comment]
Do you mean while running ssh-audit.py -n -h ?

**Comment by thecliguy** [comment]
Yes, that's correct, using `-n -h` together.

Do you see any reason against adding a new argument in `usage` that accepts an output buffer? My assumption is we could then pass a reference to the output buffer that's instantiated in `main`.

I'm happy to take a look at this if the above sounds OK...

**Comment by manfred-kaiser** [comment]
Switching to python argparse might resolve this issue: #154 

If it's ok, I will rewrite the argument parsing part.

**Comment by thecliguy** [comment]
I would strongly encourage you to get an opinon from @jtesta before investing time in writing such a change.

My only concern is that there's sometimes a tradeoff between using a programming language's own argument parsing vs rolling your own... Using a programming languages argument parsing usually means writing less code which is of course very appealing... But on the other hand, you may lose a certain degree of flexibility and have more constraints over things such as the handling of invalid arguments and the presentation of advice on the correct use of arguments.

**Comment by thecliguy** [comment]
@jtesta : Hello, long time no speak...

I've submitted PR #162 so that the usage text now respects `-n` and `--no-colors`.

The tox test is failing but I don't think it's failing on code that I've worked on in this change...

Please can you review the change and if the tox failures are due to me then please let me know and I'll try to address them.  

Here's a couple of examples of this change in action:

**WITH COLOR**
![WithColor](https://user-images.githubusercontent.com/23440389/216793976-c94e9478-be7b-4748-9868-b8c0293463a0.PNG)

**WITHOUT COLOR**
![WithoutColor](https://user-images.githubusercontent.com/23440389/216793981-758b5d90-39fc-4f96-99bb-a284197b9128.PNG)
