### ISSUE TITLE
Add more servers and clients to the vulnerability database

### ISSUE THREAD

**Issue by hmaier1996** [jtesta/ssh-audit#155]
At the moment only OpenSSH, Dropbear and PuTTY are covered by the [vulnerability database](https://github.com/jtesta/ssh-audit/blob/3300c60aaa3603f1683fba9454e792e270672055/src/ssh_audit/versionvulnerabilitydb.py).

A lot of servers are missing. For example [Gitea](https://gitea.io) is a git server, which has it's own ssh server implemented.
It would be good to add those applications to the ssh-audit.

It would be good to add other clients like Filezilla or WinSCP to this database.

**Comment by manfred-kaiser** [comment]
@hmaier1996 version fingerprinting for gitea is not possible, because the banner is "SSH-2.0-Go".

The only usfull information is the programming language "go".
Adding a entries to the vulnerability database might not be possible for all server implementions.

**Comment by hmaier1996** [comment]
thanks for the information. Gitea was only an example for other servers :disappointed: 

Perhaps there are other servers, which provide more information :wink:

**Comment by jtesta** [comment]
> It would be good to add other clients like Filezilla or WinSCP to this database.

I wouldn't mind adding this to the database, but realistically, I'm not sure I'd be able to keep it up-to-date in the long term.  But if someone in the community submitted a PR, I'd happily merge it!
