### ISSUE TITLE
Dropbear ssh hardening guide addition

### ISSUE THREAD

**Issue by graysky2** [jtesta/ssh-audit#159]
The current release of dropbear can be hardened by building it adding the following three lines to `localoptions.h`:
```
#define DROPBEAR_RSA_SHA1 0
#define DROPBEAR_DH_GROUP14_SHA1 0
#define DROPBEAR_SHA1_HMAC 0
```

Wondering if you would like to add this to your hardening guide.

Reference: https://github.com/mkj/dropbear/issues/138

**Comment by jtesta** [comment]
I've updated the website (https://www.ssh-audit.com/hardening_guides.html) and the wiki (https://github.com/jtesta/ssh-audit/wiki/Dropbear-2022.83) with this.  Thanks for contributing!
