### ISSUE TITLE
cast128-ctr and blowfish-ctr are listed as fail and/or warn, but aren't part of recommendations at end

### ISSUE THREAD

**Issue by ckalinwi** [jtesta/ssh-audit#16]
cast128-ctr and blowfish-ctr (correctly) fail in the client (-c) report: 

[snipped]

# encryption algorithms (ciphers)
(enc) aes256-gcm@openssh.com                -- [info] available since OpenSSH 6.2
(enc) aes128-gcm@openssh.com                -- [info] available since OpenSSH 6.2
(enc) aes256-ctr                            -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52
(enc) aes192-ctr                            -- [info] available since OpenSSH 3.7
(enc) blowfish-ctr                          -- [fail] removed (in server) since OpenSSH 6.7, unsafe algorithm
                                            `- [fail] disabled since Dropbear SSH 0.53
                                            `- [warn] disabled (in client) since OpenSSH 7.2, legacy algorithm
                                            `- [warn] using weak cipher mode
                                            `- [warn] using small 64-bit block size
(enc) cast128-ctr                           -- [fail] deprecated cipher
(enc) aes128-ctr                            -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52
(enc) arcfour                                 -- [fail] removed (in server) since OpenSSH 6.7, unsafe algorithm
                                            `- [warn] disabled (in client) since OpenSSH 7.2, legacy algorithm
                                            `- [warn] using weak cipher

But aren't mentioned in the recommendations report:

# algorithm recommendations
(rec) -arcfour                              -- enc algorithm to remove

A peek at the code doesn't show any obvious reason why this should happen, and I know it's minor, but the program is otherwise so thorough I felt I should let you know.

**Comment by jtesta** [comment]
Thanks for letting me know.

To speed up testing, what client & version did you encounter this with?

**Comment by ckalinwi** [comment]
Tera Term 4.105.

Your script also yelled about all the Camellia ciphers that TeraTerm has
turned on by default but I figured, given that I've seen Camellia _no where
else_ in relation to SSH, that it was a waste of time to submit those.

**Comment by jtesta** [comment]
Fixed in the `dev` branch.  I also added the missing Camellia ciphers.  I'll be making a stable release soon with them included.

Thanks for reporting this!
