### ISSUE TITLE
Ubuntu 22.04 LTS Client / Linux Mint 21 Client hardening guide added to the Wiki

### ISSUE THREAD

**Issue by XSpielinbox** [jtesta/ssh-audit#161]
Thank you for creating ssh-audit!

I've added a hardening guide for Ubuntu 22.04 to the wiki, that should be applicable to every Ubuntu 22.04 based OS too.
It can be found under https://github.com/jtesta/ssh-audit/wiki/Ubuntu-22.04-LTS-Client---Linux-Mint-21-Client

If you have any objections or recommendations, please let me know.
If there are none, I would be happy, if it could be added to the website.

**Comment by jtesta** [comment]
I've added the official guides here: https://www.sshaudit.com/hardening_guides.html

Thanks for contributing!
