### ISSUE TITLE
3072 bit moduli vs. 3071 bit moduli

### ISSUE THREAD

**Issue by XSpielinbox** [jtesta/ssh-audit#168]
As per [Source Code](https://github.com/jtesta/ssh-audit/blob/master/src/ssh_audit/gextest.py#L224) moduli smaller than 3072 are flagged with a warning as beeing insecure. However, all guides on the [website](https://ssh-audit.com/hardening_guides.html) as well as [Mozillas guides](https://infosec.mozilla.org/guidelines/openssh) treat 3071 moduli as 3072 bit DH and therefore secure. The next smaller size in the ssh-moduli file would be 2047 and the next bigger 4095 - so it seems to make more sense that ssh for some reason subtracts 1 from the size rather than them beeing so much worse.

Could you please clarify that. Either the code or the guides should be changed accordingly.

**Comment by jtesta** [comment]
Have you seen a 3071-bit key get flagged by ssh-audit?  If so, I'd like to reproduce the issue.

**Comment by jtesta** [comment]
I think this is a server-side bug in OpenSSH.
