### ISSUE TITLE
Deprecate ssh-rsa recommendation in favor of ed25519 or rsa-sha2-256/512

### ISSUE THREAD

**Issue by jauderho** [jtesta/ssh-audit#17]
As of OpenSSH 8.2, there is now notice that ssh-rsa will be deprecated in the near future.

https://www.openssh.com/releasenotes.html

> It is now possible[1] to perform chosen-prefix attacks against the
SHA-1 hash algorithm for less than USD$50K. For this reason, we will
be disabling the "ssh-rsa" public key signature algorithm that depends
on SHA-1 by default in a near-future release.

**Comment by jtesta** [comment]
[I checked in the changes](https://github.com/jtesta/ssh-audit/commit/c9a2f2955c47feab371af9f3b3e8ea7d1ff73c89) for this already into the `dev` branch.  I was planning on making a stable release with it soon, actually.

I appreciate that you pinged me about it anyway!  Glad to see that people are paying attention!
