### ISSUE TITLE
Improve Hardening Guides

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#172]
The hardening guides should include the following directives:

- `CASignatureAlgorithms`
- `GSSAPIKexAlgorithms`
- `HostbasedAcceptedAlgorithms`
- `PubkeyAcceptedAlgorithms`

**Comment by jtesta** [comment]
@XSpielinbox: Thanks for the help!  I've made updates to Ubuntu 22.04 (both server and client), Debian 12, and included the new directives in the new Rocky Linux 9 and Amazon Linux 2023 guides.

Thanks again for your help!!

**Comment by perkelix** [comment]
What's produced by the hardening guide's config generator script doesn't match what policy auditing expects on 3.1.0.

**Comment by jtesta** [comment]
Can you provide a specific example?

**Comment by perkelix** [comment]
$ ssh-audit 172.16.1.1
# general
(gen) banner: SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u2

$ ssh-audit -P "Hardened OpenSSH Server v9.2 (version 3)" 172.16.1.1
Host:   172.16.1.1
Policy: Hardened OpenSSH Server v9.2 (version 3)
Result: ❌ Failed!

Errors:
  * Host keys did not match.
    - Expected (required): rsa-sha2-512, rsa-sha2-256, ssh-ed25519
    - Expected (optional): sk-ssh-ed25519-cert-v01@openssh.com, ssh-ed25519-cert-v01@openssh.com, rsa-sha2-512-cert-v01@openssh.com, rsa-sha2-256-cert-v01@openssh.com, sk-ssh-ed25519@openssh.com
    - Actual:              ssh-ed25519, rsa-sha2-512, rsa-sha2-256

  * Key exchanges did not match.
    - Expected: sntrup761x25519-sha512@openssh.com, curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group-exchange-sha256
    - Actual:   sntrup761x25519-sha512@openssh.com, curve25519-sha256, curve25519-sha256@libssh.org, diffie-hellman-group16-sha512, diffie-hellman-group18-sha512, diffie-hellman-group-exchange-sha256, kex-strict-s-v00@openssh.com

**Comment by jtesta** [comment]
Ahh, ok.  If this is Debian 12, I suppose I'll take a closer look,
then.  Thanks for reporting!

**Comment by jtesta** [comment]
Could you please open a new issue to track this?  That would be helpful
to make sure I don't forget about it, since the present issue is
already closed.
