### ISSUE TITLE
Update dependencies and new release

### ISSUE THREAD

**Issue by XSpielinbox** [jtesta/ssh-audit#174]
1. The Dockerfile is still using Python 3.9. Is there any special reasoning behind that? If not, I would suggest updating to the `python:3-slim` image, that uses Python 3.11 and automatically switches to newer stable 3.x versions, when available, lowering the maintenance burden.

2. The Snap still uses `core20`. Would an upgrade to `core22` be possible?

3. After these updates and the large amount of changes since 2.5.0, it would be nice if a new version would be released, that then can be packaged and downloaded by users.

Thanks in advance. If I can help in any way, please let me know.

**Comment by thecliguy** [comment]
@jtesta - Do you think it's strictly necesarry to wait for all the items above to be resolved before publishing a new release? 

Quite a few fixes and enhancements have accumulated under v2.6.0-dev now...

**Comment by jtesta** [comment]
@XSpielinbox , @thecliguy : v2.9.0 has been released!  Thanks for all your help!
