### ISSUE TITLE
CentOS 7 hardening guide: sshd-keygen recipe modifies non-config file

### ISSUE THREAD

**Issue by scop** [jtesta/ssh-audit#176]
Step 1 in current https://www.sshaudit.com/hardening_guides.html#rhel7 modifies `/usr/lib/systemd/system/sshd-keygen.service` which is not a config file. Those changes are silently overwritten on `openssh-server` package upgrades.

Here's an alternative that survives them:
```shell
mkdir -p /etc/systemd/system/sshd-keygen.service.d
cat <<\EOF > /etc/systemd/system/sshd-keygen.service.d/ssh-audit.conf
[Unit]
ConditionFileNotEmpty=
ConditionFileNotEmpty=!/etc/ssh/ssh_host_ed25519_key
EOF
systemctl daemon-reload
```

**Comment by jtesta** [comment]
It took me way too long to get to this.  My apologies.

The CentOS 7 guide has now been updated, as per your instructions.  Thank you very much for contributing!
