### ISSUE TITLE
Cisco IOS XE SSH Hardening Guide

### ISSUE THREAD

**Issue by timmayg** [jtesta/ssh-audit#178]
Would you please add this Cisco IOS XE SSH Hardening Guide that I authored to your list.   Thank you

https://community.cisco.com/t5/networking-knowledge-base/configuring-ios-xe-for-strong-security-ssh-sessions/ta-p/4556490

**Comment by jtesta** [comment]
@timmayg : the guide you linked suggests to the reader that they enable the NIST P-curves in the key exchange algorithms.  These curves are strongly suspected as being back-doored by the NSA.

If there's another guide for Cisco IOS XE that doesn't include them, I'd be happy to add it, though.  Thanks!

**Comment by timmayg** [comment]
Hey Joe

Sorry, I realize this reply is months later, but I’d like to add some comments and try and learn some more details about your feelings. 

In my guide I’ve suggested using the KEX algorithms ecdh-sha2-nistp521 & ecdh-sha2-nistp384.

The curves used in these are P-521 and P-384. These curves are also known as secp521r1 and secp384r1. 

I don’t see any evidence of suspected back doors in these NIST P-curves.  

Every time I try and find evidence about backdoors I'm pointed to stories about Edward Snowden disclosures suggesting a back door in Dual EC DRBG which is based off of the P-256. Dual EC DRBG is not based off of P-384 or P-521.   

What is your concern with the KEX algorithms I’ve recommended? 

Thanks man, I appreciate your input. 
Tim
