### ISSUE TITLE
Possible to select source interface

### ISSUE THREAD

**Issue by daniejstriata** [jtesta/ssh-audit#184]
I have some hosts with multiple interfaces where the primary interface can't connect to the hosts being scanned. Can I choose either the interface or IP to be used for the source?

**Comment by daniejstriata** [comment]
I have some bastion hosts that do not have a "normal" route out to other hosts. I doubt many other users would use this if it can be added but would make my audits a little easier.

When using scp you can specify the bind address like so
`scp -oBindAddress=192.168.0.15`
and with telnet
`telnet -b 192.168.0.15`

**Comment by thecliguy** [comment]
@daniejstriata - Please can you try the following...

Modify `ssh_socket.py` as follows...

Above `s.connect(addr)`, place the following:

```python
s.bind(('x.x.x.x', 0))
```

Replace `x.x.x.x` with the source IP address that's associated with the interface you want to use.

**Comment by daniejstriata** [comment]
@thecliguy I took your advice about the default route to heart. It's adding other complexities so I've updated the default interface. I tested your suggested change but it does not appear to make a difference. 

I downloaded the tar.gz from releases and edit `src/ssh_audit/ssh_socket.py` and updated s.bind to use an invalid IP and for some reason ssh-audit still used the default route and printed the audit results:
           ` s.bind(('10.1.1.1', self.__port))`
           ` s.bind(('::', self.__port))`

**Comment by thecliguy** [comment]
@daniejstriata - Hummm... The scan only succeeds for me if I provide a valid IP address that's bound to an interface.

If I enter an invalid IP then I get an error like this:
```
[exception] cannot connect to test.rebex.net port 22: [Errno 99] Cannot assign requested address
```

Do you think it's possible that when you are running ssh-audit, it is using an installed version instead of the modified version from the `tar.gz`?

To be sure that you are running the modified version of ssh-audit, you could add a print statement above `s.bind ...`, EG:

```python
print('hello world')
s.bind(('x.x.x.x', 0))
s.connect(addr)
```

**Comment by daniejstriata** [comment]
Thanks. Seems that was the problem. All good now.
