### ISSUE TITLE
Non-resolvable hostnames make the application quit unexpectedly.

### ISSUE THREAD

**Issue by daniel-cues** [jtesta/ssh-audit#186]
When a list of hosts is used and one of the hosts is not resolvable by DNS, the application quits. This stops any further connections or tests to the rest of the hosts

Error code: `[exception] [Errno -2] Name or service not known`

I'm working on a pull request, the bug is in **ssh_socket's _resolve function**, which for some reason exits the application when it fails to resolve a hostname.

**Comment by jtesta** [comment]
Merged in https://github.com/jtesta/ssh-audit/commit/a74c3abdde286dd74993ef65d5745f925f3dc49c.

**Comment by thecliguy** [comment]
@jtesta : Great. Apologies, at first glance it wasn't immediately obvious to me if that would happen because `.connect()` doesn't return an exit code - but I can see now that `.audit()` inspects the return value and produces an `CONNECTION_ERROR`.
