### ISSUE TITLE
Algorithm recommendations categorised as 'chg' are always treated as failures

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#188]
The comment that accompanies an RSA hostkey with a modulus size less than 3072 bits is treated as a warning and is thus printed as such _(by setting the level of an OutputBuffer to 'warn', see `ssh_audit.py` > `output_algorithm`)_:

![image](https://github.com/jtesta/ssh-audit/assets/23440389/842137b1-6cd4-4bfd-9640-99202e73c2f1)

However, the "Algorithm Recommendations" section prints the advice to increase the modulus size as a failure:

![image](https://github.com/jtesta/ssh-audit/assets/23440389/3f1f8f18-5c43-48c6-8be7-655d3d56e92b)

The latter behaviour is caused by all recommendations categorised as `chg` being printed with `out.fail`. This behaviour can be fixed by updating `ssh_audit.py` > `output_recommendations` to use `out.warn` if the level of the current algorithm is `warning`.

@jtesta : Please can you advise if you'd be happy for this change to be made before I spend time writing a PR?

**Comment by jtesta** [comment]
@thecliguy : sorry for the late response.  Sure, that PR would be helpful.  Thanks!

**Comment by thecliguy** [comment]
@jtesta : Please can you review #196.

**Comment by jtesta** [comment]
Merged.  Thanks again for your help!
