### ISSUE TITLE
Add guide for FreeBSD Server/Client

### ISSUE THREAD

**Issue by jlduran** [jtesta/ssh-audit#189]
https://github.com/jtesta/ssh-audit/wiki/FreeBSD-OpenSSH-Hardening-Guides

Obtained from: https://github.com/bsdlabs/ssh-hardening

**Comment by jtesta** [comment]
@jlduran : Thanks for submitting this!  What version of FreeBSD does this apply to?

**Comment by jlduran** [comment]
> @jlduran : Thanks for submitting this! What version of FreeBSD does this apply to?

It should apply to all [supported FreeBSD releases](https://www.freebsd.org/releases/), we also test against a recent-ish (1-2 weeks old depending on GCE) stable/current branch.

**Comment by jtesta** [comment]
Ok.  What specific versions did you test against?  I'd prefer putting the exact version numbers into the guides, that way users in the future can see if the instructions are stale.

**Comment by jlduran** [comment]
> Ok. What specific versions did you test against? I'd prefer putting the exact version numbers into the guides, that way users in the future can see if the instructions are stale.

Absolutely:
- 12.4-RELEASE
- 12.4-STABLE
- 13.2-RELEASE
- 13.2-STABLE
- 14.0-CURRENT

**Comment by jtesta** [comment]
I added the wiki link to https://www.sshaudit.com/hardening_guides.html.  Thanks for writing the guide!
