### ISSUE TITLE
The Same Instance of SSH2_KexDB is Used When Scanning Multiple Targets

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#190]
I believe there are occasions throughout the existing code where `SSH2_KexDB` is being instantiated with global scope. Consequently, when scanning multiple targets (irrespective of multithreading), this can lead to each target reading and modifying the same instance of `SSH2_KexDB`.

I've found a few issues that I believe to be caused as a result of this...

  * If a target supports multiple RSA signature algorithms, the intention is to parse the RSA hostkey once, rather than once per signature algorithm. This logic is being misapplied when dealing with multiple targets... Once the first target with an RSA hostkey is scanned, all subsequent targets with an RSA host key skip parsing. https://github.com/jtesta/ssh-audit/blob/2d5a97841fa4c4411acabcc51d194af4a9ee7b32/src/ssh_audit/hostkeytest.py#L108-L110

  * Once the first target with an RSA hostkey is scanned, comments relating to the modulus size of that target are applied to all subsequent targets with an RSA host key. This can be very misleading, for example, if the first target had a 2048-bit modulus, these comments will now be applied to all targets with an RSA hostkey, irrespective of its modulus size. https://github.com/jtesta/ssh-audit/blob/2d5a97841fa4c4411acabcc51d194af4a9ee7b32/src/ssh_audit/hostkeytest.py#L217-L223

  * Every time a target is encountered with `diffie-hellman-group-exchange-256`, `post_process_findings` in `ssh_audit.py` appends another comment. This means the second target with `diffie-hellman-group-exchange-256` will have two duplicate comments, the third will have three and so on... https://github.com/jtesta/ssh-audit/blob/2d5a97841fa4c4411acabcc51d194af4a9ee7b32/src/ssh_audit/ssh_audit.py#L448-L452
  
I don't know if this is an extensive list of issues... There may be more?

@jtesta : I think a code review is needed to find out full extend of this problem...

**Comment by jtesta** [comment]
@thecliguy : fixed in https://github.com/jtesta/ssh-audit/commit/639f11a5e576a8bc6f34b68d76ceca7b879b7418.  Thank you very much for researching and reporting this bug!!
