### ISSUE TITLE
Probable wrong order for HostKeyAlgorithms on "Hardened Ubuntu Client 22.04 LTS (version 1)" | breaking host certificate verification

### ISSUE THREAD

**Issue by alexandrestein** [jtesta/ssh-audit#193]
Hello,

Applying the "expected" host keys for "Hardened Ubuntu Client 22.04 LTS (version 1)" breaks certificate authentication.
A simple reorder (placing certificate algorithms first) solves the issue.

The "expected" value is:
`ssh-ed25519, ssh-ed25519-cert-v01@openssh.com, sk-ssh-ed25519@openssh.com, sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256, rsa-sha2-256-cert-v01@openssh.com, rsa-sha2-512, rsa-sha2-512-cert-v01@openssh.com`
But I would propose this:
`sk-ssh-ed25519-cert-v01@openssh.com, sk-ssh-ed25519@openssh.com, ssh-ed25519-cert-v01@openssh.com, ssh-ed25519, rsa-sha2-256, rsa-sha2-256-cert-v01@openssh.com, rsa-sha2-512, rsa-sha2-512-cert-v01@openssh.com`

I'm not an expert, but I guess this does not negatively impact security, while preserving support for additional features on top of the base algorithms.
I don't use SK variant, so I didn't test those.

Let me know if that make sense.

Kind regards,
Alex

**Comment by jtesta** [comment]
Hi Alex.  I seem to have trouble reproducing this issue.  From a clean Ubuntu Server 22.04 image, I created an ED25519 CA, signed the ED25519 host key with it, and added the following to `/etc/ssh/sshd_config`:

```
HostKey /etc/ssh/ssh_host_ed25519_key
HostCertificate /etc/ssh/ssh_host_ed25519_key-cert.pub
```

I verified that the server certificate was properly offered using ssh-audit:
```
$ ssh-audit localhost
[...]
# host-key algorithms
(key) ssh-ed25519                           -- [info] available since OpenSSH 6.5
(key) ssh-ed25519-cert-v01@openssh.com (256-bit cert/256-bit ssh-ed25519 CA) -- [info] available since OpenSSH 6.5
[...]
```

I then copy-pasted the expected host key values that the "Hardened Ubuntu Client 22.04 LTS (version 1)" client policy wants into my `~/.ssh/config` file.  I was still able to connect to the server.

Could you please show your server's `HostKey` and `HostCertificate` settings?  And could you please show your local `~/.ssh/config` file as well?  Then I could try to set up a test environment most similar to yours.  Thanks in advance!

**Comment by alexandrestein** [comment]
The order don't break connection on it's own but you lost certificate validation
You are still able to connect but it does not check the validity of the certificates it goes directly to ask you to confirm the public key.

Maybe I was not clear this is the client config I'm referring to.

The example with "my line":
```
debug1: Server host certificate: ssh-ed25519-cert-v01@openssh.com SHA256:xl9NsP0da3yhlhkJInukMbjNlKjxaw6aoheRvjv8O/k, serial 496 ID "Panoramix" CA ssh-ed25519 SHA256:jgrAK4kJO4wXhzimYHa5ycdr4kghxw8x6OLWAY49M08 valid forever
debug1: load_hostkeys: fopen /home/alexandre/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '192.168.1.1' is known and matches the ED25519-CERT host certificate.
debug1: Found CA key in /home/alexandre/.ssh/known_hosts:3
```

When I use the recommended line:
```
debug1: Server host key: ssh-ed25519 SHA256:xl9NsP0da3yhlhkJInukMbjNlKjxaw6aoheRvjv8O/k
debug1: load_hostkeys: fopen /home/alexandre/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: hostkeys_find_by_key_hostfile: hostkeys file /home/alexandre/.ssh/known_hosts2 does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
The authenticity of host '192.168.1.1 (192.168.1.1)' can't be established.
ED25519 key fingerprint is SHA256:xl9NsP0da3yhlhkJInukMbjNlKjxaw6aoheRvjv8O/k.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

I attached the client config file.

I'm a bit short on spare time to work on this currently but I'll try to share a docker image with all you will need to reproduce your self.
It's a production server I don't want to publish anything from it.

I'm running on the client 9.2p1-2 and server 8.4p1-5+deb11u1.

Please let me know if you need anything more.

**Comment by jtesta** [comment]
@alexandrestein : I've updated the "Hardened Ubuntu Client 22.04 LTS" in the command line tool from version 1 to 2, which re-prioritizes the host key types.  I've also updated the client hardening guide (at https://ssh-audit.com/hardening_guides.html#ubuntu_22_04_linux_mint_21) to reflect this change as well.

Please re-open this issue if you run into any more problems.  Thanks for reporting!
