### ISSUE TITLE
curve448 KEX algorithm

### ISSUE THREAD

**Issue by ktcherenkov** [jtesta/ssh-audit#195]
We found a new key exchange algorithm 'curve448-sha512@libssh.org' when testing Titan FTP server NextGen from South River Technologies. It uses new elliptic curve [curve448](https://en.wikipedia.org/wiki/Curve448). Currently, it's not recognized by ssh-audit. Output from ssh-oudit:

# general
(gen) banner: SSH-2.0-TitanFTP_2.1.0.2174
(gen) compatibility: OpenSSH 7.3+ (some functionality from 6.6), Dropbear SSH 2016.73+
(gen) compression: enabled (zlib)

# key exchange algorithms
(kex) ecdh-sha2-nistp521             -- [fail] using elliptic curves that are suspected as being backdoored by the U.S. National Security Agency
`- [info] available since OpenSSH 5.7, Dropbear SSH 2013.62
(kex) ecdh-sha2-nistk409
(kex) ecdh-sha2-nistb409
(kex) ecdh-sha2-nistt571
(kex) ecdh-sha2-curve25519
(kex) curve25519-sha256@libssh.org   -- [info] available since OpenSSH 6.4, Dropbear SSH 2013.62
                                     `- [info] default key exchange since OpenSSH 6.4
(kex) curve448-sha512@libssh.org     -- [warn] unknown algorithm
(kex) diffie-hellman-group14-sha256  -- [warn] 2048-bit modulus only provides 112-bits of symmetric strength
                                     `- [info] available since OpenSSH 7.3, Dropbear SSH 2016.73

**Comment by jtesta** [comment]
@ktcherenkov : thanks for reporting this!  I just added this algorithm to the `master` branch.
