### ISSUE TITLE
more streamlined output

### ISSUE THREAD

**Issue by perkelix** [jtesta/ssh-audit#202]
The output currently uses a separate line to indicate since when a feature has been the default e.g.:

```
(kex) curve25519-sha256@libssh.org        -- [info] available since OpenSSH 6.4, Dropbear SSH 2013.62
                                          `- [info] default key exchange since OpenSSH 6.4
```

This could be simplified as:

```
(kex) curve25519-sha256@libssh.org        -- [info] default since OpenSSH 6.4, available since Dropbear SSH 2013.62
```

The part of the line that states a default could be highlighted in e.g. blue instead of green.

**Comment by jtesta** [comment]
Similar to #253, this seems to be a matter of personal preference.  Furthermore, the community vote in #253 showed a preference for leaving the current formatting as-is.
