### ISSUE TITLE
FYI: Synology DSM page added

### ISSUE THREAD

**Issue by matsimon** [jtesta/ssh-audit#204]
Hi

I wanted to give you a heads-up that I have added a page for the embedded OS that Synology ships on their NAS devices as they at least provide some customization in the area of ciphers, MAC and KEX: [Synology DSM](https://github.com/jtesta/ssh-audit/wiki/Synology-DSM)

Unfortunately the host keys don't seem to be configurable in a supported way thus similar to Aruba AOS-S I've added a disclaimer section at the bottom of the page. Thank you @jtesta for your continued effort for ssh-audit!

**Comment by jtesta** [comment]
@matsimon : Thanks for writing the guide!  I've added a link on https://www.ssh-audit.com/hardening_guides.html for it.

Thanks again!!
