### ISSUE TITLE
JSON (-jj;--json) severity output (info|warn|fail)

### ISSUE THREAD

**Issue by OblackatO** [jtesta/ssh-audit#207]
Firstly let me thank you for this great project and the work the maintainers put on it. 

When using the options *--json* or *-jj*, the severity of the results is not output.

For instance, when not using JSON, the output of the **key exchange algorithms** section could look like the following: 
```txt
...
# key exchange algorithms
(kex) curve25519-sha256                     -- [info] available since OpenSSH 7.4, Dropbear SSH 2018.76
                                            `- [info] default key exchange since OpenSSH 6.4
(kex) curve25519-sha256@libssh.org          -- [info] available since OpenSSH 6.4, Dropbear SSH 2013.62
                                            `- [info] default key exchange since OpenSSH 6.4
(kex) diffie-hellman-group16-sha512         -- [info] available since OpenSSH 7.3, Dropbear SSH 2016.73
(kex) diffie-hellman-group18-sha512         -- [info] available since OpenSSH 7.3
(kex) diffie-hellman-group-exchange-sha256 (2048-bit) -- [warn] 2048-bit modulus only provides 112-bits of symmetric strength
...
```

When using JSON *(-jj)*, the output above looks like the following:
```json
...
  "kex": [
        {
            "algorithm": "curve25519-sha256"
        },
        {
            "algorithm": "curve25519-sha256@libssh.org"
        },
        {
            "algorithm": "diffie-hellman-group16-sha512"
        },
        {
            "algorithm": "diffie-hellman-group18-sha512"
        },
        {
            "algorithm": "diffie-hellman-group-exchange-sha256",
            "keysize": 2048
        }
    ],
...
```
This [line](https://github.com/jtesta/ssh-audit/blob/02ab487232de438c0811116f2676cb1c9b5f3d62/src/ssh_audit/ssh_audit.py#L1259C1-L1259C30) suggests this was done on purpose....

May I ask what was the motivation behind this implementation? 
I believe that letting the user know what the severity of some result is, in the JSON output, could greatly benefit additional parsing processes.

I also didn't find any other options that allow me to get the severity levels in the JSON output. I tied both **--verbose** and **--debug**. Am I missing something here?

**Comment by thecliguy** [comment]
What you're asking for was added in the latest version ([3.0.0](https://github.com/jtesta/ssh-audit/releases/tag/v3.0.0), released on 2023-09-07).

So, I assume you have an older version of ssh-audit.

To find out what version of ssh-audit you have, run `ssh-audit -h` and check the first line of output.
