### ISSUE TITLE
 FYI: FortiOS and RouterOS pages added

### ISSUE THREAD

**Issue by matsimon** [jtesta/ssh-audit#209]
Hi Joe

Since I have had some time to work with Fortinet and Mikrotik devices recently I have added pages for FortiOS and RouterOS:
 * [Fortinet FortiOS](https://github.com/jtesta/ssh-audit/wiki/Fortinet-FortiOS)
 * [Mikrotik RouterOS](https://github.com/jtesta/ssh-audit/wiki/Mikrotik-RouterOS)

While have not been able to validate against each version (especially with Fortinet) I've tried to add references so readers can do validate them if they need to. Both vendors have shown in the past, they change configuration knobs within major version so I hope I got them right by digging through their documentation.

Since both embedded OS provide a limited about of configurability for SSH, there is both a disclaimer section and for the versions that I have actually validated my results.

**Comment by jtesta** [comment]
@matsimon : Thanks for writing these!  I've added links to them on https://www.ssh-audit.com/hardening_guides.html.
