### ISSUE TITLE
There is no any warning when MACs are not presented

### ISSUE THREAD

**Issue by JustasM11** [jtesta/ssh-audit#219]
```$ ssh-audit -h
# ssh-audit v3.0.0, https://github.com/jtesta/ssh-audit
```

**Prerequisites:**
SSH server is missing any MACs, e.g. build dropbear using:
```
#define DROPBEAR_SHA1_HMAC 0
#define DROPBEAR_SHA2_256_HMAC 0
#define DROPBEAR_SHA2_512_HMAC 0
#define DROPBEAR_SHA1_96_HMAC 0
```

**Steps:**
1. Execute ssh-audit vs server
**Expected:**
Warning about missed MACs
**Actual:**
No note about missing MACs:

```
$ ssh-audit 10.142.1.233
# general
(gen) banner: SSH-2.0-dropbear_2022.83
(gen) software: Dropbear SSH 2022.83
(gen) compatibility: OpenSSH 7.3+, Dropbear SSH 2016.73+
(gen) compression: disabled

# key exchange algorithms
(kex) curve25519-sha256@libssh.org   -- [info] available since OpenSSH 6.4, Dropbear SSH 2013.62
                                     `- [info] default key exchange since OpenSSH 6.4
(kex) diffie-hellman-group14-sha256  -- [warn] 2048-bit modulus only provides 112-bits of symmetric strength
                                     `- [info] available since OpenSSH 7.3, Dropbear SSH 2016.73
(kex) kexguess2@matt.ucc.asn.au      -- [info] available since Dropbear SSH 2013.57

# host-key algorithms
(key) ssh-ed25519                    -- [info] available since OpenSSH 6.5
(key) rsa-sha2-256 (0-bit)        -- [info] available since OpenSSH 7.2

# encryption algorithms (ciphers)
(enc) chacha20-poly1305@openssh.com  -- [info] available since OpenSSH 6.5
                                     `- [info] default cipher since OpenSSH 6.9
(enc) aes128-ctr                     -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52
(enc) aes256-ctr                     -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52

# fingerprints
(fin) ssh-ed25519: SHA256:xJWz/STr0Su5rcbHhOe3k2UiMxBkdZGTnAaa25ncVPE
(fin) ssh-rsa: SHA256:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU

# algorithm recommendations (for Dropbear SSH 2022.83)
(rec) +curve25519-sha256             -- kex algorithm to append 
(rec) +diffie-hellman-group16-sha512 -- kex algorithm to append 
(rec) +twofish128-ctr                -- enc algorithm to append 
(rec) +twofish256-ctr                -- enc algorithm to append 
(rec) -diffie-hellman-group14-sha256 -- kex algorithm to remove 

```

**Additional info:**
https://security.stackexchange.com/a/33576

**Comment by jtesta** [comment]
The fact that no MAC is offered by the server is ok, considering
there's an authenticated cipher in the cipher list (
***@***.***).  An explicit MAC isn't needed since
that cipher will handle integrity assurance.

However, a MAC would be needed for the aes128-ctr & aes256-ctr ciphers.
 What happens when you try to connect with an OpenSSH client and give
it the "-oCiphers=aes256-ctr" argument?  Does a successful connection
get made?  I would guess not.  And I would hope not, too!

The second thing that jumps out at me is this:

> (key) rsa-sha2-256 (0-bit) -- [info] available since OpenSSH 7.2

Looks like ssh-audit failed to obtain the RSA key size.  What version
of Dropbear did you run it against?  Might you be able to re-run it
with the -d flag and show the debugging output it produces?  That would
be a big help!

**Comment by JustasM11** [comment]
>  What happens when you try to connect with an OpenSSH client and give
> it the "-oCiphers=aes256-ctr" argument?  Does a successful connection
> get made? 
> 
No:
```
$ ./ssh -V
OpenSSH_9.5p1, OpenSSL 1.1.1n  15 Mar 2022

$ ./ssh -oCiphers=aes256-ctr root@10.142.1.233
Unable to negotiate with 10.142.1.233 port 22: no matching MAC found. Their offer: 
```

> What version of Dropbear did you run it against? 
```
# dropbear -V
Dropbear v2022.83
```

> Might you be able to re-run it with the -d flag and show the debugging output it produces? 
Unfortunately I cannot reproduce this issue, I see the following now:
```
(key) rsa-sha2-256 (2048-bit)        -- [warn] 2048-bit modulus only provides 112-bits of symmetric strength
                                     `- [info] available since OpenSSH 7.2
```

**Comment by JustasM11** [comment]
@jtesta Please feel free to close it if it is not an issue.

**Comment by jtesta** [comment]
I'd say this is a minor bug in Dropbear: it shouldn't be advertising ciphers without built-in integrity if its not offering any MAC algorithms.  But as far as ssh-audit goes, it seems to be properly working.  It is entirely valid for a server to offer the `chacha20-poly1305` cipher and other authenticated encryption algorithms without any MACs.  So I don't think any warning from ssh-audit would be in order.

If you're able to reproduce the "rsa-sha2-256 (0-bit)" output, though, please open a new issue!  That would be important to fix.  Thanks!
