### ISSUE TITLE
MacOS guide - success on 14.1 Sonoma

### ISSUE THREAD

**Issue by JonCellini** [jtesta/ssh-audit#220]
As requested wanted to let you know the [MacOS guide](https://github.com/jtesta/ssh-audit/wiki/macOS) works as expected on MacOS 14.1 (Sonoma). 

`Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64`

**Comment by jtesta** [comment]
I've updated the wiki with this information.  Thanks for letting me know!
