### ISSUE TITLE
MacOS Guide - Works With macOS Ventura

### ISSUE THREAD

**Issue by jdwhite** [jtesta/ssh-audit#221]
As requested, [this guide](https://github.com/jtesta/ssh-audit/wiki/macOS) works with macOS Ventura.

`Darwin example.com 22.6.0 Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 x86_64`

**Comment by jtesta** [comment]
I've updated the wiki with this information.  Thanks for letting me know!
