### ISSUE TITLE
Setting Minimum DH Gex Sizes > 2048 is Ineffective with OpenSSH

### ISSUE THREAD

**Issue by scolby33** [jtesta/ssh-audit#223]
There are several default policies for OpenSSH that include `'dh_modulus_sizes': {'diffie-hellman-group-exchange-sha256': 4096}`. Unfortunately, according to my reading of the relevant OpenSSH source ([here](https://github.com/openssh/openssh-portable/blob/80a2f64b8c1d27383cc83d182b73920d1e6a91f1/dh.c#L202) and [here](https://github.com/openssh/openssh-portable/blob/80a2f64b8c1d27383cc83d182b73920d1e6a91f1/dh.c#L472-L484)), [this group thread](https://groups.google.com/g/opensshunixdev/c/WBzeSrf1mm8), and testing against OpenSSH 9.5 on OpenBSD, this is ineffective. Removing smaller moduli from `/etc{,/ssh}/moduli` will result in OpenSSH falling back to the standard groups 14, 16, or 18, depending on the requested size from the client.

For example:
```console
$ uname -a
OpenBSD hostname 7.4 GENERIC.MP#0 amd64
$ sshd -V
OpenSSH_9.5, LibreSSL 3.8.2
$ awk '{ print $5 }' /etc/moduli | sort -u
4095
6143
8191
$ ssh-audit --gex-test '1-9000:1' localhost
# diffie-hellman group exchange modulus size
diffie-hellman-group-exchange-sha256 --> 2048, 4096, 6144, 8192
```

I'm not sure what the right thing to do here is. Probably documenting this in the hardening guides and adding notes about the ineffectiveness of removing small moduli should happen. It's also interesting that with a policy forbidding, e.g., 2048-bit moduli, the standard ssh-audit passes.

**Comment by jtesta** [comment]
Prior to ssh-audit v3.0.0, the tool would trigger the fallback mechanism and warn that 2048-bit moduli are supported.  This lead to confusion when admins did update their moduli file.  So in v3.0.0, I added logic to ignore the case of 2048-bit moduli being found against OpenSSH servers.  My rationale was that this fallback would only be triggered in rare real-world scenarios, but triggered all the time in testing scenarios.

I just responded to issue #206, where I go into a bit more detail on this matter.  In fact, let's consolidate discussion to that issue, and I'll close this one.
