### ISSUE TITLE
Mismatch between server guide and tests' expected modulus size

### ISSUE THREAD

**Issue by m3tra** [jtesta/ssh-audit#224]
First of all thank you for building such a useful tool Joe.

Test environment:
Fresh VM install of each OS  listed below and online Policy Audit test

Regarding the policy audits:
`Hardened Ubuntu Server 16.04 LTS (version 3)`
`Hardened Ubuntu Server 18.04 LTS (version 3)`
`Hardened Ubuntu Server 20.04 LTS (version 3)` (which could be listed with `Debian Bullseye (Debian 11)` since their guides are equal)
`Hardened Ubuntu Server 22.04 LTS (version 3)` (which could be listed with `Debian Bookworm (Debian 12)` since their guides are equal)
Expected modulus size: 4096
Actual modulus size set with online guide: 3072

Should the guides for all of them share the 4096 size or were these specific tests' "expected setting" wrongfully defined as 4096?

If this situation is correct as is, could you help me understand why the differences? I'm inexperienced so any knowledge from an industry professional such as yourself would be greatly appreciated.

I would also ask that, if possible, the OSs that have an equal recommended config share a list entry in the online tester. It would help those who have opted to harden their base Debian servers

**Comment by jtesta** [comment]
Fixed in the `master` branch in 69e1e121fdea7c521580da1a42cdf4a1f4123b83.  Thanks for reporting this!

> I would also ask that, if possible, the OSs that have an equal recommended config share a list entry in the online tester. It would help those who have opted to harden their base Debian servers

Are you referring to the policy audit drop-down box on the web front-end (ssh-audit.com)?  If so, could you give a concrete example of what you'd like to see?
