### ISSUE TITLE
chacha20-poly1305@openssh.com append/remove ping pong recommendation

### ISSUE THREAD

**Issue by scop** [jtesta/ssh-audit#229]
Initial state on a server I ran current master branch against:
```
# algorithm recommendations (for OpenSSH 9.2)
(rec) +sntrup761x25519-sha512@openssh.com   -- kex algorithm to append 
(rec) -chacha20-poly1305@openssh.com        -- enc algorithm to remove 
```
After removing `chacha20-poly1305@openssh.com`:
```
# algorithm recommendations (for OpenSSH 9.2)
(rec) +chacha20-poly1305@openssh.com        -- enc algorithm to append 
(rec) +sntrup761x25519-sha512@openssh.com   -- kex algorithm to append 
```
(`sntrup761x25519-sha512@openssh.com` probably has nothing to do with this, but included output here verbatim in case it happens to matter after all.)

**Comment by jtesta** [comment]
I just pushed a fix to the `master` branch.  Thanks for reporting!
