### ISSUE TITLE
"using small 512-bit CA key modulus" misleading

### ISSUE THREAD

**Issue by philfry** [jtesta/ssh-audit#239]
Hi,

I'm running an SSH-CA with ECDSA to sign my host keys (in this example an ed25519 host key).
ssh-audit complains about

> (key) ssh-ed25519-cert-v01@openssh.com (256-bit cert/512-bit ecdsa-sha2-nistp256 CA) -- [fail] using small 512-bit CA key modulus
> (rec) -ssh-ed25519-cert-v01@openssh.com       -- key algorithm to remove

Since ECDSA does not have a modulus the failure is misleading. The check either should only apply to RSA CAs or be adapted to support elliptic curve CAs key sizes.

Thanks!

**Comment by jtesta** [comment]
Thanks for reporting this!  It should be fixed in 73b669b49d1a86617495e504d2987ff276f28360.

Note that this still results in a scan failure, since the NIST P-curves are suspected of being back-doored.  But the code now properly handles the modulus.
