### ISSUE TITLE
Add ElementTree or CSV module for csv/xml reports

### ISSUE THREAD

**Issue by WSLUser** [jtesta/ssh-audit#24]
I'd like to be able to get a csv or xml report of the audit. Json manipulation is great but it's easier to add better reporting options.

Related:
https://github.com/arthepsy/ssh-audit/issues/5

**Comment by jtesta** [comment]
I'd be happy to merge code to add CSV and/or XML reports, but its not a 
personal priority of mine to write that code.  I suppose your options 
would be to submit a PR for it, or possibly sponsor a paid bounty for 
someone in the community to add it.

Same goes for issue #25 regarding MS Word/LibreOffice exports.

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by jtesta** [comment]
Unless you'll be submitting a PR for it, or sponsoring a bounty for it, I'm closing this issue since it doesn't make sense to track it.
