### ISSUE TITLE
Add support for OpenSSH8.1 and 8.2

### ISSUE THREAD

**Issue by WSLUser** [jtesta/ssh-audit#26]
8.2 in particular adds support for FIDO sticks but there are a number of other improvements and changes that probably require more checks be added (including CVEs). https://www.openssh.com/releasenotes.html

I did see you started working a tiny bit on it in your dev branch so this issue should be a tracker for visibly showing support for these versions.

**Comment by jtesta** [comment]
In ssh-audit v2.2.0, I added support for these new host key types: 
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com, 
sk-ecdsa-sha2-nistp256@openssh.com, sk-ssh-ed25519-cert-v01@openssh.com, 
and sk-ssh-ed25519@openssh.com.

Are any other algorithms missing?

Also: what specific CVE checks are missing?

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by jtesta** [comment]
I'm closing this since specific details aren't included.  If you can point to specific algorithms or CVE's, however, please re-open it.
