### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by erikvanoosten** [jtesta/ssh-audit#27]
It would be great if there are installation instructions.

I discovered that on Mac with Homebrew you can do: ```brew install ssh-audit```

On Debian and Ubuntu you can do: ```apt install ssh-audit```

**Comment by jtesta** [comment]
There are installation instructions in the dev branch already, actually: 
https://github.com/jtesta/ssh-audit/tree/dev

I can add the notes for Homebrew, though.

And FYI, the Debian and Ubuntu packages are still using the original 
code from arthepsy (at least for the time being).  Debian's unstable 
branch just recently switched to my fork, so eventually end users will 
have access to it.  Not sure how long that will take.

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by genbtc** [comment]
Great news about debian. 
Also you can get the updated version directly through pythons package manager with pip:
If this is the first time you've done so, You might need to install pip first:
`sudo apt-get install python3-pip`
Then:
`pip3 install ssh-audit` 
And it will download it from pypi @ https://pypi.org/project/ssh-audit/ and install it.
This puts it into ~/.local/bin , and might print a message complaining about the PATH.
`source .profile` on my Debian 10 system then reloaded this dir into my PATH. or:
`PATH="$HOME/.local/bin:$PATH"` adds it manually.

**Comment by jtesta** [comment]
Closing this, since the `dev` branch has updated instructions now.
