### ISSUE TITLE
Missing "keysize" Information in Output

### ISSUE THREAD

**Issue by dreizehnutters** [jtesta/ssh-audit#275]
The .json output does not contain consitant information about host keys in the "key" section:

![grafik](https://github.com/jtesta/ssh-audit/assets/7869385/e50d10c2-84b8-41d5-9b0f-6e51faabb93a)

I would expect that for each key the "keysize" information is also presented.

![grafik](https://github.com/jtesta/ssh-audit/assets/7869385/1b7dea0c-ce0c-48bd-9f4b-473c05d45edf)

**Comment by dreizehnutters** [comment]
open PR:
https://github.com/jtesta/ssh-audit/pull/276

**Comment by jtesta** [comment]
The original intention was to provide key size information only for types that are variable, such as RSA.  ED25519 and NISTP* all have fixed-size keys, so it would just be redundant information being given back to the user.

**Comment by dreizehnutters** [comment]
I see your point @jtesta. I personly would prefer a more consitant output format.

**Comment by jtesta** [comment]
Let's allow the community to decide this issue, then.  We'll take votes on this matter from now until October 1 (almost a 3-month window).

Anyone who wants the JSON output updated to always include key size information, place a thumbs-up emoji (:+1:) on this comment.  Anyone who thinks the current behavior should remain (key size information is only given for variable-sized key types), place a thumbs-down emoji (:-1:) on this comment.

I'll implement whatever behavior the community wants after Oct. 1, 2024.
