### ISSUE TITLE
Script recommends impossible -ssh-rsa modification for Ubuntu 18.04 LTS.  Debian 10 Buster works.

### ISSUE THREAD

**Issue by genbtc** [jtesta/ssh-audit#28]
First of all I want to say I love your script.
On Ubuntu 18.04 LTS systems (+latest updates) = SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3 , 
with your latest ssh-audit (2.2.0) , there is some issue with -ssh-rsa, that isnt there on Debian. 
I think it could be related to a bug in the OpenSSH version.
I can't follow the hardening guide directly to remove my RSA host key entirely, so I have just re-generated it with 4096 bit, but still ran into an issue. 
**No amount of sshd_config configuration will simultaneously allow me to keep the rsa-sha2 version active while disabling the weak sha1 one**. I believe its due to the confusion between "ssh-rsa" and "rsa-sha2" (indirectly mentioned on here https://utcc.utoronto.ca/~cks/space/blog/tech/OpenSSHAndSHA1Deprecation and possibly related to this bug differentiating the two, which persists on ALL my systems, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854650 )

On Ubuntu 18.04 LTS The script reports this:
```# host-key algorithms
(key) ssh-ed25519                           -- [info] available since OpenSSH 6.5
(key) ssh-rsa (4096-bit)                    -- [fail] using weak hashing algorithm
                                            - [info] available since OpenSSH 2.5.0, Dropbear SSH 0.28
(key) rsa-sha2-512 (4096-bit)               -- [info] available since OpenSSH 7.2
(key) rsa-sha2-256 (4096-bit)               -- [info] available since OpenSSH 7.2
...
# algorithm recommendations (for OpenSSH 7.6)
(rec) -ssh-rsa                              -- key algorithm to remove 
```
In the sshd_config, I have this Line (also for HostBasedAcceptedKeyTypes):
`HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa`

**Removing ONLY the "ssh-rsa" off the end of the line, results in ALL of my RSA host key being completely disabled.** The script reports that all three RSAs get removed, even the SHA2 ones that were OK.
This behavior doesn't add up, because doing the same thing on **Debian 10 Buster = SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2 works properly** and does NOT result in this complete RSA disablement, and the config files are otherwise identical.
I can only assume theres an issue in this Ubuntu 7.6 version of OpenSSH and if thats the case, your script needs to know about it, so it can issue a warning saying disabling the weak one will also disable the safe ones.
Running `ssh-keygen -lf ssh_host_rsa_key` produces 4096 SHA256:XXYYZZABC123etc so I'm pretty sure the key itself is valid SHA2.
If you know of a workaround or would like me to test any further stuff, let me know.
Thank You for undertaking this security project. Also, I support you and all your endeavors, after I found out about your valiant failed attempts to get DJM to add X448 curves on the OpenSSH mailing list, and then the dead maintainer on the old broken audit script, which you succeeded with on Debian. Keep up the good work!

**Comment by jtesta** [comment]
> Removing ONLY the "ssh-rsa" off the end of the line, results in ALL of my RSA host key being completely disabled.

Yep, that's known behavior for the OpenSSH version shipped with Ubuntu 18.04.  It wasn't until one of the later versions that they fixed it so that `ssh-rsa` can be disabled individually in the server config.

The good news is that the version shipped in Ubuntu 20.04 works as it should; you can individually disable `ssh-rsa` while leaving `rsa-sha2-256` and `rsa-sha2-512` enabled.

One option is to keep RSA host keys enabled, but disable `ssh-rsa` in your client.  The OpenSSH client in Ubuntu 18.04 supports this (it's only the server's support which is broken in this version).  Be careful with PuTTY, though... client hardening doesn't quite work the way with that as you'd expect...

> Thank You for undertaking this security project. Also, I support you and all your endeavors, after I found out about your valiant failed attempts to get DJM to add X448 curves on the OpenSSH mailing list, and then the dead maintainer on the old broken audit script, which you succeeded with on Debian. Keep up the good work!

Glad to hear my hard work is appreciated!  And glad to hear that you've gotten good use out of the script!

**Comment by genbtc** [comment]
Thank you for the quick response. Good thing you already know about this issue, I was not able to find exact info confirming or denying it myself, and I think it would help to make a short specific note of this somewhere, either in the script or on the hardening page with the Ubuntu instructions, as 18.04 LTS is still supported until 2023, and common for servers still, and so too is RSA. I will have to undertake the upgrade to 20.04 LTS sooner now. Having my eyes opened to client side hardening is also a new frontier to me, and I will definitely be applying those extra rules to my machine too. As for the meanwhile, maybe this issue thread will the message to other people, but you can close it if you want. Thanks!

**Comment by jtesta** [comment]
Glad I could help!
