### ISSUE TITLE
Inconsitent JSON Output Format

### ISSUE THREAD

**Issue by dreizehnutters** [jtesta/ssh-audit#280]
Depending on the audit mode used (policy vs non-policy scan), the tool outputs different keys in the JSON format. Additional information within the policy output format about the target port is missing.

policy audit:
![grafik](https://github.com/jtesta/ssh-audit/assets/7869385/ba0ac5f1-bfa4-42e1-b193-9cb6d6b4446e)

normal audit
![grafik](https://github.com/jtesta/ssh-audit/assets/7869385/af4555a5-4094-47ae-a361-3da58c0df3d6)

**Comment by jtesta** [comment]
Fixed in https://github.com/jtesta/ssh-audit/commit/bc2a89eb11325b57b7dd675c75bc26e63c5dec52.
