### ISSUE TITLE
policies suggest different orders

### ISSUE THREAD

**Issue by perkelix** [jtesta/ssh-audit#283]
There are inconsistencies between policies when it comes to the order in which options should appear.

Hardened Debian 12 (version 1) wants 

`chacha20-poly1305@openssh.com, aes256-gcm@openssh.com, aes128-gcm@openssh.com, aes256-ctr, aes192-ctr, aes128-ctr`

while Hardened Ubuntu Server 24.04 LTS (version 1) wants

`chacha20-poly1305@openssh.com, aes256-gcm@openssh.com, aes256-ctr, aes192-ctr, aes128-gcm@openssh.com, aes128-ctr`

Likewise, for host keys, Hardened Debian 12 (version 1) wants 

`rsa-sha2-512, rsa-sha2-256, ssh-ed25519 `

while Hardened Ubuntu Server 24.04 LTS (version 1) wants 

`ssh-ed25519, rsa-sha2-512, rsa-sha2-256`

The order should remain consistent between policies, unless there's a compelling reason not to. If there is, the rational for the exception should be explained.

**Comment by jtesta** [comment]
I added a version 2 of the Debian 12 policy to bring it in line with the Ubuntu 24.04 policy.  I also updated the hardening guide on the website as well (https://ssh-audit.com/hardening_guides.html#debian_12).
