### ISSUE TITLE
Feature Request: Output Directory and SSH Auth Methods

### ISSUE THREAD

**Issue by l4rm4nd** [jtesta/ssh-audit#290]
Hi @jtesta ,

many thanks for this great project!

## SSH Auth Methods

It would be nice to include some info about the supported auth methods of an SSH server. For example `password`, `public key` and/or `keyboard-interactive`. Regarding hardening, only pubkey auth should be offered as the other ones allow brute-forcing attacks and password guessing (if no measures are implemented such as fail2ban etc.).

I personally would flag all as info but you may define password and keyboard-interactive as warning.

## Output Directory

I am currently relying on the JSON output. However, there seems no possibility to define the output directory or output file at all via CLI params. The only way is to pipe the Python's script output into an outfile. This works fine but gets problematic when ssh-audit is called from another script via subprocess. I always have to overwrite the `stdout`, which is a bit weird.

Would be nice if you add an argparse argument to define the output dir.

You can limit this to the `-j` and `-jj` output formats if you want.

**Comment by jtesta** [comment]
> many thanks for this great project!

Thanks!  A lot of the initial formation of this project was done by @arthepsy; I handled all new features and planning since 2019.

> It would be nice to include some info about the supported auth methods of an SSH server.

I agree, though unfortunately that information is buried too far into the SSH handshake for us to obtain.  Adding the code to extract it would be very complex, and quite frankly, not worth the effort to write and maintain over time.

> I always have to overwrite the stdout, which is a bit weird.

Could you elaborate more on this weirdness?  The way I imagine it, using `subprocess.run(..., stdout=subprocess.PIPE)` would let the calling program read stdout easily; it could then write the output to a file as needed.

**Comment by l4rm4nd** [comment]
> that information is buried too far into the SSH handshake for us to obtain. Adding the code to extract it would be very complex, and quite frankly, not worth the effort to write and maintain over time.

Alright. Guess it's not worth adding then. Thanks for the explanatiln though.

Regarding the subprocess thing you are right. I can pipe the stdout and gain access to the results this way. I am doing it like this already.

I was just curious as many other tools often have a specific cli option to define the output location. Would make it a bit more easy for me and I would not have to pipe stdout. 

Not that big of an issue though. Just something to consider for the future maybe.

**Comment by l4rm4nd** [comment]
Just a small py code to tinker with:

````py
import paramiko

def check_ssh_auth_methods(server, port=22):
    try:
        # Create a transport object
        transport = paramiko.Transport((server, port))
        transport.start_client()

        # Attempt to authenticate with no credentials to trigger the exception
        transport.auth_none('')  # Sends an empty username to query methods

    except paramiko.ssh_exception.SSHException as e:
        # Parse the allowed authentication types from the exception message
        allowed_types_start = "allowed types: "
        if allowed_types_start in str(e):
            allowed_types = str(e).split(allowed_types_start)[-1]
            methods_list = eval(allowed_types)  # Safely parse the list from the string
            for method in methods_list:
                print(f"(auth) {method}")
    except:
        # Suppress all other errors silently
        pass
    finally:
        try:
            transport.close()
        except:
            pass
````

Just returns the auth methods for an SSH server.

**Comment by jtesta** [comment]
@l4rm4nd : thanks for this.  Those `start_client()` and `auth_none()` methods are deceptively simple, though.  They initiate an encrypted channel with the server, which is far beyond what ssh-audit has the ability to do without the use of a crypto/SSH library.  And while it is certainly possible to use paramiko, one of the original design goals was to be a very lightweight tool with no external dependencies.

That said, I started a discussion in #311 to consider whether we should change course on that original decision.

Thanks again for this example code!
