### ISSUE TITLE
JSON mode break JSON parser

### ISSUE THREAD

**Issue by LoHub** [jtesta/ssh-audit#295]
In some cases ssh-audit in JSON mode print regular output for warning or error, which break JSON parsing with other tools.
Would it be possible to only print information in JSON format or display non JSON content in stderr instead of stdout?

See example:

```bash
$ ssh-audit -c --json 
Warning: failed to listen on any IPv6 interfaces.

$ ssh-audit -c --json | jq
parse error: Invalid numeric literal at line 1, column 8
```

Thank you very much.

**Comment by jtesta** [comment]
I believe this is now fixed.  If you're able to confirm the fix, that would be a big help!  Or if you find that the problem still exists, please re-open this issue.

Thanks for reporting!

**Comment by azizalali-code** [comment]
Still appears to be broken

**Comment by jtesta** [comment]
> Still appears to be broken

Can you please provide the steps you took to reproduce the problem?
