### ISSUE TITLE
Flake8 issues

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#30]
In #29 I disabled all Flake8 warnings for now - as there are just too many. The plan is to tackle them one by one once the test suite is passing again.

Also, in future `setup.py` and the tests should be linted.

While most of the issues are easy to fix, @jtesta maybe you want to have a look at the dictionary key 'ecdsa-sha2-1.3.132.0.10'  - which seems to be declared twice. This easy to avoid issue shows that it is very desirable to get a working linter and test suite back again.

```
948   E117 over-indented
26    E126 continuation line over-indented for hanging indent
50    E128 continuation line under-indented for visual indent
2     E226 missing whitespace around arithmetic operator
8     E231 missing whitespace after ','
24    E251 unexpected spaces around keyword / parameter equals
24    E261 at least two spaces before inline comment
20    E265 block comment should start with '# '
2     E301 expected 1 blank line, found 0
6     E302 expected 2 blank lines, found 1
8     E303 too many blank lines (2)
1     E305 expected 2 blank lines after class or function definition, found 1
1     E711 comparison to None should be 'if cond is not None:'
2     E712 comparison to False should be 'if cond is False:' or 'if not cond:'
3     E722 do not use bare 'except'
4     E741 ambiguous variable name 'l'
2     F601 dictionary key 'ecdsa-sha2-1.3.132.0.10' repeated with different values
14    F841 local variable 'e' is assigned to but never used
4     W504 line break after binary operator
7     W605 invalid escape sequence '\s'
1156
```

**Comment by jugmac00** [comment]
I fixed quite some Flake8 errors - I created PR #35 for all applied fixes.

If you want, you can merge the PR already - as it is self contained.

I left some Flake8 warnings on purpose, e.g. the indentation (mixed tabs and spaces) and over-/under-indented warnings...
Fixing those would literally mean changing every line, which I would not mind, but I wanted to ask before I do this.

Also, I did not fix E501 (line too long), as I do not know what your preference is about that (e.g. 80, 100, .. or try to fix all errors?)

I also did not fix E722 (bare except), as I am not familiar enough with the code base - yet.

Also, there is lots of data formatted in a tabular way, which breaches E241 (multiple spaces after operator) - but I guess this should be kept that way.

https://github.com/jtesta/ssh-audit/blob/e447c42a79df49841d5269eacde6dbeb811a6be4/ssh-audit.py#L1906-L2011

So, what is your take on these remaining Flake8 issues?

Do you know https://github.com/psf/black ? `Black` would fix most of these formatting issues by the push of a button, but .. .not everybody likes `Black`.

**Comment by jugmac00** [comment]
I also noticed, that the test files are not checked by Flake8 - this will be done as a next step.

**Comment by jtesta** [comment]
I think it would be easier for me to fix the issues that affect every line (like space/tab indent mixing).  If you could provide the exact command used to find these, that would make it easier for me.  I'm not (yet) familiar with flake8 and other tools.

> Also, I did not fix E501 (line too long), as I do not know what your preference is about that

80 character line limitations are obsolete.  People have high-res screens with very long lines these days, so it's not an issue.  That, and splitting lines breaks `grep`.  So I'd rather ignore long line warnings.

> Also, there is lots of data formatted in a tabular way, which breaches E241 (multiple spaces after operator) - but I guess this should be kept that way.

Yes, the current formatting improves readability and maintainability, so it should be kept.

> Do you know https://github.com/psf/black ?

I've never used it.  I just read about it now, and it seems like there's not many configuration options, by design.  I think I'll add it to my own to-do list to experiment with and see if I like it.  Give me a week or so and I'll have a decision one way or another.

**Comment by jtesta** [comment]
I addressed most of the flake8 warnings in my latest commit to `dev`.  I'm very glad to be rid of tabs now!

The only two warnings we are ignoring now are for lines too long and the tables of dictionaries.  Both of those I think we can leave.

Thanks for driving this process forward!
