### ISSUE TITLE
Supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#31]
In #5 you mentioned:

> Python 3.5 is the minimum version I'm supporting.

What does this mean to Python 2.7?

- remove Python 2.7 from tox?
- remove Python 2.7 from travis?
- remove comp. code for Python 2.7?
ie
https://github.com/jtesta/ssh-audit/blob/bbc4ab542d6797eceeb80995ec7814d15f1dd9de/ssh-audit.py#L37-L51

_Originally posted by @jtesta in https://github.com/jtesta/ssh-audit/issues/5#issuecomment-636365917_

**Comment by jtesta** [comment]
> What does this mean to Python 2.7?

Python 2 is now unsupported.  Last I checked, it may still work, but it may stop working at any time without notice.

If you wanted to remove all Python 2 things, feel free!

**Comment by jugmac00** [comment]
Python 2.6, 3.3 and 3.4 have been droppend in #29.

I kept Python 2.7 for now, dropping it means also changes to the source code, and the PR #29 is already quite big.

Dropping Python 2.7 is another PR.

**Comment by jtesta** [comment]
My strategy was to just ignore Python 2 support and let it decay.  But if someone wanted to jump in and work to remove the old stuff, I'll certainly merge it.
