### ISSUE TITLE
Support for type hints / annotations - currently 189 errors

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#32]
With #29 I got the mypy check at least running again, and it now shows:

    Found 189 errors in 1 file (checked 1 source file)

What is your take on typing?

Currently, tox runs the mypy checks, but I changed the tox setting so it does not fail the tox run.

Maybe this is something to look into once Python 2 is dropped completely and then one could use type annotations instead of type comments?

This is an area in Python I have not much experience yet, as I mostly worked in Python 2 code bases until recently.

**Comment by jtesta** [comment]
I'm a huge fan of strongly-typed languages.  Adding type hints to the code would be great!

Unfortunately, I don't think I could prioritize it for this project.  At least, I wouldn't have the time to do it myself.  If someone else wanted to take this up, however, I'd be happy to merge it!

**Comment by jugmac00** [comment]
This is the next one on my list.

**Comment by jtesta** [comment]
Great!  I look forward to it!

**Comment by jugmac00** [comment]
Basic typing errors were fixed with #39.

Currently open to do:
- enable stricter mypy options one by one and fix the errors
- convert type comments to annotations

I had a deeper look at the latter one, and I am on a good track, but there are some caveats, as
- type annotations for variables were introduced with Python 3.6 (until then we have to use comments for variable annotation)
- type annotations for e.g. class factories need special treatment

For class factories, you need to wrap the class name in quotes or from Python 3.7 on you can import `from __future__ import annotations`, cf https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7
The future import is no longer necessary with Python 3.10 :-)

**Comment by jtesta** [comment]
I enabled more mypy checks, which now all pass.  Is there anything else left to enable?  I think I got them all.

**Comment by jugmac00** [comment]
Looks great!

As I mentioned, this was my first (bigger) project applying type hints in Python, so nothing else to add from my side.

I think this is a great addition. It is much easier to reason about the code, less chance for bugs, and really nice autocompletion support in my IDE!

**Comment by jtesta** [comment]
Great!  I suppose I'll close this now that it's complete.  Thanks again for getting most of this done!
