### ISSUE TITLE
Jenkins integration still wanted?

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#34]
Hi,

when upgrading the used `pytest` version, the following warning is issued:
```
.tox/py38-test/lib/python3.8/site-packages/_pytest/junitxml.py:417
  /home/jugmac00/Projects/ssh-audit/.tox/py38-test/lib/python3.8/site-packages/_pytest/junitxml.py:417: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
```

Is it ok to drop the xml generation or do you use it?

It is triggered by
`test: pytest -v --junitxml={toxinidir}/reports/junit.{envname}.xml {posargs:test}`

=> I currently set `pytest` < 6.0

**Comment by jtesta** [comment]
I don't particularly feel strongly about Jenkins integration, unless it would find issues we can't already.

But if you particularly felt compelled to get it working, feel free!
