### ISSUE TITLE
Please use a tag to signify a new release

### ISSUE THREAD

**Issue by graysky2** [jtesta/ssh-audit#4]
This will help maintainers of the package.

**Comment by jtesta** [comment]
I was already planning that.  ;)

But what package maintainers are you referring to?

**Comment by graysky2** [comment]
This package is the [AUR](https://aur.archlinux.org/packages/ssh-audit/) so at least Arch and clones are using it.

**Comment by jtesta** [comment]
Gotcha.  I see that you notified them that development is continuing on my repo.  Thanks for that!

**Comment by jtesta** [comment]
Done.  v2.0.0 has been released!

**Comment by graysky2** [comment]
Updated, thanks.

https://aur.archlinux.org/cgit/aur.git/commit/?h=ssh-audit&id=01297ea0ecdb92560d8a81ffe032709bb4a88432

**Comment by jtesta** [comment]
Great!

I noticed, though, that the "url" field of the SRCINFO and PKGBUILD files still point to arthepsy's branch instead of mine.

**Comment by graysky2** [comment]
Dammit... `vimdiff` error on my part.  Fixed now.

https://aur.archlinux.org/cgit/aur.git/commit/?h=ssh-audit&id=685c73a7d9d67060766b8bfd4313913235e27f2f
