### ISSUE TITLE
RuntimeError when auditing SSH-Server

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#41]
```
❯ python3.8 ssh-audit.py xx.xxx.xxx.xxx -p 22022 --json
Traceback (most recent call last):
  File "ssh-audit.py", line 3103, in <module>
    main()
  File "ssh-audit.py", line 3099, in main
    audit(conf)
  File "ssh-audit.py", line 3088, in audit
    print(json.dumps(build_struct(banner, kex=kex, client_host=s.client_host), sort_keys=True))
  File "ssh-audit.py", line 2996, in build_struct
    for host_key_type in host_keys.keys():
RuntimeError: dictionary keys changed during iteration
```

This is reproducible for one of my old, inherited SSH Servers, but not for the new one, which I configured after your guide.

I can provide you the address in private if you need it to debug.

Anyway, the problem is pretty obvious, and the exception says it clearly. It is no good idea to change an Iterable while iterating over it.

The fix is trivial - just wrap `host_keys.keys()` from above in a `list()`.

The above line is not covered by a test, though, as all the JSON generation. So, this is good chance to raise test coverage.

I'll try to find some time and create a PR for this issue.

**Comment by jtesta** [comment]
Yes, please e-mail me the server's address and I can take a look at it (jtesta at-sign positronsecurity.com).  Thanks!

**Comment by jtesta** [comment]
@jugmac00 I didn't hear back about this, so I thought I'd follow up.  I'm hoping to get a release done in the next couple weeks, so fixing this would be great if possible!

**Comment by jugmac00** [comment]
@jtesta Sorry for not getting back to you earlier and thanks for the ping!

With the typing issues I already had 2 open PRs which needed to be merged one after another, and I also wanted to wait until you fix the remaining typing issue, until I create another PR.

Too much branching and dependency on the order of merging makes it pretty fast complicated :-)

Also, although I watch this repository I did not get a notification when you pushed your latest work. I guess that is because you did not create a PR.

But here we go - PR is ready to be reviewed.

Looking forward to the new release! :rocket:

**Comment by jtesta** [comment]
Did merged PR #44 fix this issue?

**Comment by jugmac00** [comment]
Yes!

```
❯ python3.8 ssh-audit.py xx.xxx.xxx.xxx -p 22022 --json
{"banner": {"comments": null, "protocol": [2, 0], ......
```

I am not used to these long running dev branches, so I was not sure whether this issue should be closed or not, as it is not fixed on master, yet.

**Comment by jtesta** [comment]
Glad it's fixed!

The reason I keep a long-term dev branch is because I know users are lazy and they check out the master branch by default.  So I keep master == latest stable release, and put all pre-release code into dev.  That way, users get the latest release by default, instead of potentially broken alpha/beta code by default.

I've been closing issues when they're fixed in dev, since until recently, this fork wasn't too popular.  Now I might have to re-think this for user-facing issues like this one, since release users (i.e.: master branch) can run into issues that are outstanding for them, but fixed in dev...

**Comment by jugmac00** [comment]
Thanks for the explanation!

At the other projects I contribute, master is not a place for broken software either, as usually there is a strong test suite and merges are only allowed after a pull request review. Certainly, more maintainers are needed for such a setup to work out.
