### ISSUE TITLE
Unused variables when unpacking

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#42]
I just saw the following code
```
                        unused = None  # pylint: disable=unused-variable
                        unused2 = None  # pylint: disable=unused-variable
                        unused, unused2, err = s.get_banner()
```
In Python, for variables which value does not matter, usually you use an underscore.

So, above code could (and should) be rewritten into
```
                        _, _, err = s.get_banner()
```

cf
https://oliver.bestwalter.de/articles/something-i-really-must-underscore/#simply-it-needs-a-name-but-i-won-t-use-it

P.S.: I did not update the code as I am in midst of the typing issue. Maybe you want to label this one as "good-first-issue"?

**Comment by jtesta** [comment]
> Maybe you want to label this one as "good-first-issue"?

Done!
