### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#5]
Travis CI needs to be enabled on this repo.  This may take quite a lot of tweaking to get working...

**Comment by jugmac00** [comment]
Currently, also `tox` is broken in every possible way :-)

I had a look at the `tox` config and tried to get `tox` passing. It isn't too bad - except for tons of linting errors (and one test I could not make passing).

Before I create a pull request, can you tell me
- what versions of Python do you plan to support?
- against which branch should I create the pull request? What is your development model? As I saw, you have a very long going `dev` branch?

Thanks for maintaining this great package!

**Comment by jtesta** [comment]
Glad to hear you're interested in fixing this!  Python 3.5 is the minimum version I'm supporting.

And yes, please submit to the `dev` branch.  Thanks!

**Comment by jugmac00** [comment]
Thanks for merging the PR!

Could you please activate Travis for this repository, and also setup a weekly "Cron Job" for the `master` and the `dev` branches?
(Travis -> Repository -> More Options -> Settings -> Cron Jobs)

**Comment by jtesta** [comment]
Done!
