### ISSUE TITLE
Confusion: ecdsa-sha2-nistpXXX family is claimed as weak

### ISSUE THREAD

**Issue by Firm** [jtesta/ssh-audit#55]
ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521 are claimed as 'weak' when enabled in HostKeyAlgorithms. But OpenSSH directs to use them as one of possible algorithms (see: https://www.openssh.com/txt/release-8.2):

The better alternatives include:

 * The RFC8332 RSA SHA-2 signature algorithms rsa-sha2-256/512. These
   algorithms have the advantage of using the same key type as
   "ssh-rsa" but use the safe SHA-2 hash algorithms. These have been
   supported since OpenSSH 7.2 and are already used by default if the
   client and server support them.

 * The ssh-ed25519 signature algorithm. It has been supported in
   OpenSSH since release 6.5.

 * The RFC5656 ECDSA algorithms: ecdsa-sha2-nistp256/384/521. These
   have been supported by OpenSSH since release 5.7.

**Comment by jtesta** [comment]
Sorry for the late response.

The idea that the NIST curves are weak and possibly back-doored is not agreed upon by the crypto community.  Some (including myself) think that there's enough evidence that they should be avoided.  Thankfully, there are better alternatives such as Curve25519.
