### ISSUE TITLE
GSSAPI Key Exchange (gssapi-keyex) Algorithms

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#57]
I've no particular interest in using GSSAPI key exchange algorithms and can't claim to understand how they work, my question simply concerns whether `ssh-audit` should be capable of detecting these algorithms if present...

I've been working with [Bitvise SSH Server](https://www.bitvise.com/ssh-server) version 8.43 and noticed that there are six `gss-*` Key Exchange Algorithms (four of which are enabled by default):

```
Enabled by default:
  1. gss-gex-sha1 with Kerberos
  2. gss-group15-sha512 with Kerberos
  3. gss-group14-sha256 with Kerberos
  4. gss-group14-sha1 with Kerberos

Disabled by default:
  5. gss-group16-sha512 with Kerberos
  6. gss-group1-sha1 with Kerberos
```

When I audit a machine running Bitvise SSH Server, the four enabled `gss-*` algorithms are not detected. I'm not sure if this is because the server lacks some prerequisite for presenting these KEX algorithms or if `ssh-audit` is failing to detect them.

I've checked the `ssh-audit` catalogue of KEX algorithms (`SSH2.KexDB.ALGORITHMS['kex']`) to see whether it contains these algorithms. I think that 1, 4 and 6 are present but the others are not:

```
     Bitvise KEX Name                    Equivalent ssh-audit KEX Name
     ----------------                    -----------------------------
  1. gss-gex-sha1 with Kerberos          gss-gex-sha1-
  2. gss-group15-sha512 with Kerberos    ?
  3. gss-group14-sha256 with Kerberos    ?
  4. gss-group14-sha1 with Kerberos      gss-group14-sha1-
  5. gss-group16-sha512 with Kerberos    ?
  6. gss-group1-sha1 with Kerberos       gss-group1-sha1-
```

I've also looked into OpenSSH's _(version 8.2p1)_ GSSAPI Key Exchange implementation, `man sshd_config`:

```
GSSAPIKexAlgorithms
        The list of key exchange algorithms that are accepted by GSSAPI key exchange. Possible values are

           gss-gex-sha1-,
           gss-group1-sha1-,
           gss-group14-sha1-,
           gss-group14-sha256-,
           gss-group16-sha512-,
           gss-nistp256-sha256-,
           gss-curve25519-sha256-

        The default is “gss-gex-sha1-,gss-group14-sha1-”.  This option only applies to protocol version 2 connections using GSSAPI
```

Again, the `ssh-audit` catalogue of KEX algorithms (`SSH2.KexDB.ALGORITHMS['kex']`) seems to contain some of the algorithms but not others:

```
     OpenSSH Algorithm Name    Present in ssh-audit?
     ----------------------    ---------------------
  1. gss-gex-sha1-             Yes
  2. gss-group1-sha1-          Yes
  3. gss-group14-sha1-         Yes
  4. gss-group14-sha256-       No
  5. gss-group16-sha512-       No
  6. gss-nistp256-sha256-      No
  7. gss-curve25519-sha256-    No
```

So my questions are:
  1. Should `ssh-audit` be capable of detecting enabled GSSAPI key exchange algorithms?
  2. Should the missing algorithm names I've listed (from Bitvise Server and OpenSSH) be added to `SSH2.KexDB.ALGORITHMS['kex']`?

**Comment by jtesta** [comment]
Sorry for the late response!

> Should ssh-audit be capable of detecting enabled GSSAPI key exchange algorithms?

Yes, although it depends on the server configuration.  For example, OpenSSH will advertise the `ssh-ed25519` host key type, but not `ssh-ed25519-cert-v01@openssh.com` unless the server is configured with a certificate of this type.  So ssh-audit will only see `ssh-ed25519`.  Likewise, the GSSAPI key exchanges are only advertised if the server was configured to use, say, Kerberos.

I installed the Bitvise, and verified that it does not advertise the GSSAPI key exchanges by default.

> Should the missing algorithm names I've listed (from Bitvise Server and OpenSSH) be added to SSH2.KexDB.ALGORITHMS['kex']?

Yes.  I added the following key exchange algorithms to the `dev` branch just now:

- `gss-group14-sha256-`
- `gss-group15-sha512-`
- `gss-group16-sha512-`
- `gss-nistp256-sha256-`
- `gss-curve25519-sha256-`

FYI, if ssh-audit encounters a new algorithm it doesn't know about, it will output the following at the end:

`!!! WARNING: unknown algorithm(s) found!: [new alg].  Please email the full output above to the maintainer (xxxx@xxxx.com), or create a Github issue at <https://github.com/jtesta/ssh-audit/issues>`
