### ISSUE TITLE
GH Action: Add Super-Linter

### ISSUE THREAD

**Issue by WSLUser** [jtesta/ssh-audit#60]
Add the recently released Github Super Linter https://github.com/github/super-linter for python as a GH action (it's in the GH Action Marketplace).

From their README:

> The end goal of this tool:
> 
> Prevent broken code from being uploaded to the default branch (Usually master)
> Help establish coding best practices across multiple languages
> Build guidelines for code layout and format
> Automate the process to help streamline code reviews
> 

**Proposed technical implementation details (optional)**
Just add the action and choose the linters for usage. For this project that should include pylint and mypy. You could optionally add others but those two provide the most coverage. I noticed usage of mypy at least has already started. So this helps provide linter errors in PRs.

**Comment by jtesta** [comment]
Thanks for the suggestion.  The project is already using pylint and mypy in the `dev` branch, which will be released as v2.3.0 "soon".  Once that happens, I can take a look at this Super Linter and see if it makes things easier.

**Comment by jugmac00** [comment]
> The project is already using pylint and mypy

And also Flake8.

Also, currently the project is using `Travis` instead of ` gh actions` for CI.

Currently, I see no gain in using the `super-linter`.

**Comment by WSLUser** [comment]
You can use both though Travis should be replaced by CircleCI, which supercedes it.

**Comment by jtesta** [comment]
I'm happy to use the best tool for the job.

@WSLUser What advantage does CircleCI have over Travis?  More specifically: how can this specific project benefit from switching over?  You'd have to make a case for why we should switch.

**Comment by WSLUser** [comment]
For now, I am only focusing on this issue. I'm perfectly willing to add the super-linter to the project myself. I am waiting for acceptance in another project first to see if I need to do anything further with it. I remember seeing some blog posts about CircleCI but I've not kept up with it. I have seen a number of large projects adopt it though.

**Comment by jtesta** [comment]
I appreciate the interest in helping, but the blocking factor is that neither the Super-Linter nor CircleCI would solve any real problem that we have.  At least... not that I can see at this point.  But if you can show specific improvements they'd grant us, I'd be interested in using them.

If you'd like to contribute to the project in other ways, though, we could use help with issues #42, #63, #66.
