### ISSUE TITLE
questionable benefit of `deepsource`

### ISSUE THREAD

**Issue by jugmac00** [jtesta/ssh-audit#70]
Of the 669 reported issues ( https://deepsource.io/gh/jtesta/ssh-audit/run/98d70105-a8f9-4aa6-8e98-1d1a401ee421/python/ ) at very least 658 are false positives, as the assert statements are used in tests, and the "unused arguments in functions" are standard pytest fixtures.

The remaining 11 "problems" are also reported by flake8 or pylint.

So I suggest to remove the `deepsource.io` integration - currently, this is just noise.

**Comment by jtesta** [comment]
Yeah, I would agree.  I thought I'd experiment with it back when it was in my `dev` branch.  But now it looks like it's more trouble than it's worth.
