### ISSUE TITLE
Restore Appveyor Testing Under Windows

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#72]
The project used to have testing done under Windows on [Appveyor](https://www.appveyor.com/docs/windows-images-software/) (see `.appveyor.yml` config file).

It is currently disabled, however.  It would be nice to get this functional again, as Windows builds are officially supported.

Alternatively, Travis is in the process of building support for Windows tests, though as of this writing, it is very limited and does not support Python projects (see [docs here](https://docs.travis-ci.com/user/reference/windows/)).  If enough time passes and this issue remains open, it would be worth checking to see if Travis's Windows support has improved.

**Comment by WSLUser** [comment]
You should actually use Azure Pipelines instead for CI/CD. It's free for OSS projects so you should be able to get an account and configure everything.

**Comment by jugmac00** [comment]
GitHub Actions could be a successor for both Appveyor and Travis (which severly restrict their free open source plans)

https://github.com/features/actions

There is no reason to hurry, though.

The advantage of GitHub actions would be the tight integration with GitHub, the timely updates (See Python 3.9), and one platform for all os tests.

They suffer from a serious injection vuln currently, though.

**Comment by jtesta** [comment]
@jugmac00 I'm open to using GitHub Actions, eventually.  Getting Windows testing would be nice to have, but not something to rush.

**Comment by jugmac00** [comment]
For reference
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by jtesta** [comment]
Closing this issue since #170 tracks the goal more appropriately.
