### ISSUE TITLE
Case Insensitive Look Up

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#73]
I think that the `--lookup` parameter should perform a case insensitive comparison.

Currently, this works:

```
ssh-audit.py --lookup=aes256-ctr
```

...But this doesn't:
```
ssh-audit.py --lookup=AES256-CTR
```

@jtesta Do you have any objection to this change? I'm happy to work on it and to submit a PR.

**Comment by jtesta** [comment]
According to OpenSSH's source code, algorithm names are case-sensitive (see https://github.com/openssh/openssh-portable/blob/396d32f3a1a16e54df2a76b2a9b237868580dcbe/match.c#L292).  So `alg1` and `ALG1` are distinct.

However, if the user asks for something we don't know about, we can output something like `alg1 was not found, but the following similar algorithms are known: ALG1, ALG2.`

**Comment by thecliguy** [comment]
@jtesta You're right, the [SSH Protocol Architecture RFC](https://tools.ietf.org/html/rfc4251) seems to concur with this.

Excerpt from section 6, page 10:
```
   In this protocol, all algorithm and method identifiers MUST be
   printable US-ASCII, non-empty strings no longer than 64 characters.
   Names MUST be case-sensitive.
```

I will look into your idea of outputting something like `alg1 was not found, but the following similar algorithms are known: ALG1, ALG2.`

**Comment by thecliguy** [comment]
Hello @jtesta ,

I now have a working case-insensitive look up that operates as follows...

Currently, if an algorithm cannot be found when a `--lookup` is performed then it is listed under the heading `# unknown algorithms`. This will continue to be the case but in addition, any algorithm not found is now searched for to find any matching similar algorithms. 

The search for similar algorithms is case-insensitive and also returns substrings. For example, searching `RSA-sha2-256` would return both `rsa-sha2-256` and `rsa-sha2-256-cert-v01@openssh.com`. The resultant suggestions are placed under the heading `# suggested similar algorithms`, where they are formatted as follows: `<USER-SUPPLIED-NAME> --> (<ALG-TYPE>) <ALG-NAME-IN-DICTIONARY>`

Here's an example usage:

```
./ssh-audit.py --lookup="AES256-gcm@openssh.com,aes128-ctr,foo,RSA-sha256,gss-group14"

# encryption algorithms (ciphers)
(enc) aes128-ctr             -- [info] available since OpenSSH 3.7, Dropbear SSH 0.52

# unknown algorithms
AES256-gcm@openssh.com
foo
RSA-sha256
gss-group14

# suggested similar algorithms
AES256-gcm@openssh.com --> (enc) aes256-gcm@openssh.com
RSA-sha256 --> (key) x509v3-sign-rsa-sha256@ssh.com
RSA-sha256 --> (key) ssh-rsa-sha256@ssh.com
gss-group14 --> (kex) gss-group14-sha1-
gss-group14 --> (kex) gss-group14-sha1-toWM5Slw5Ew8Mqkay+al2g==
gss-group14 --> (kex) gss-group14-sha256-
gss-group14 --> (kex) gss-group14-sha256-toWM5Slw5Ew8Mqkay+al2g==
```

If you're happy with this implementation then I'll submit a PR.

**Comment by jtesta** [comment]
Yeah, that sounds good.  Bonus points if your PR passes the Tox tests 
too!  (Though this isn't required... see CONTRIBUTING.md.)

FYI, early this week I'm planning on making another release, so if 
you're able to submit it by Tuesday, there's a good chance it'll be 
included!

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by thecliguy** [comment]
Thank you. PR submitted, see #80.

**Comment by jtesta** [comment]
Merged!
