### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#79]
In version 2.2.0, the Windows build consisted of a single EXE file.

Whereas in version 2.3.0, it consists of multiple files.

It's not a big deal but a single EXE just made the app a little more portable.

So I was just wondering why this has changed?

**Comment by jtesta** [comment]
I wanted to make a single EXE for v2.3.0 as well, but the fact that the 
policy files were external made things more difficult.  So in the short 
term, I had to generate the release differently.

In #75, I was able to migrate the built-in policies to an internal 
database, so packaging in Windows (and other platforms) will be easier. 
The next Windows release will be a single EXE again.

Glad to hear someone's using the Windows version!

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security
