### ISSUE TITLE
Detach from unmaintained upstream version

### ISSUE THREAD

**Issue by rugk** [jtesta/ssh-audit#8]
Maybe you can detach this repo from the not maintained fork?

You can this either [do it manually](https://www.quora.com/Git-revision-control-How-can-one-detach-a-forked-project-in-GitHub#ld_fjxjzo_52503) **or** – which I recommend – just contact the GitHub support to do it for you.

This…
1. shows that this is a real maintained project and not just a repo of someone who (once) made a pull request
2. linking to the original repo on every page does not make sense anymore as it has been discontinued/is not maintained anymore and you…
3. can (and IMHO should) still link to the original repo/website/author/… for crediting them, but you can do so in better ways (in the Readme, wiki or so)
4. You [can search the code](../search?type=Code) in repos not just forked, as GitHub prevents this for forked repos.
5. it just looks much nicer

**Comment by jtesta** [comment]
Thanks for the feedback!  Yes, that does make sense to do.

In the short-term, however, I'm trying to not make drastic changes in case the original author wakes up and decides he wants to continue.  I figure I should wait about 6 months or so.  After that, splitting off and making architecture changes would be fair game.

I'll keep this issue open as a reminder in February/March 2020.

**Comment by egberts** [comment]
This arena is big enough for both of you.   Forge ahead!

**Comment by jtesta** [comment]
Done!

My next goal is to get Debian, Ubuntu, and Kali to switch over to my fork.  I've reached out to the maintainers.  Hopefully it'll happen soon!
