### ISSUE TITLE
Let the order be equivalent

### ISSUE THREAD

**Issue by rubo77** [jtesta/ssh-audit#86]
```
 * MACs did not match.
    - Expected: hmac-sha2-256-etm@openssh.com, hmac-sha2-512-etm@openssh.com, umac-128-etm@openssh.com
    - Actual:   hmac-sha2-512-etm@openssh.com, hmac-sha2-256-etm@openssh.com, umac-128-etm@openssh.com
```

This sounds strange to me ;)

**Comment by jtesta** [comment]
My apologies for the late response!

The order of algorithms is actually significant, with the ones appearing first taking priority over the rest.  In this case, `hmac-sha2-256-etm@openssh.com` is slightly preferred over `hmac-sha2-512-etm@openssh.com` because it generates a smaller tag size.
