### ISSUE TITLE
ssh-rsa Host Key Algorithm 

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#87]
@jtesta Hi Joe

The [OpenSSH 8.3 release notes](https://www.openssh.com/txt/release-8.3) includes a future deprecation notice where it says:
_"...we will be disabling the "ssh-rsa" public key signature algorithm by default in a near-future release"_.

Is it worth updating `ssh-rsa` in `ssh2_kexdb.py` to mention something like _"A future deprecation notice has been issued in OpenSSH 8.3, see https://www.openssh.com/txt/release-8.3."_ ?

When I researched the deprecation of `ssh-rsa`, there seems to be a degree of confusion about the whole thing. So before you do anything, it's probably a good idea to check and make sure that you agree with my interpretation and that I'm not perpetuating incorrect information.

**Comment by thecliguy** [comment]
Correction...

I believe this future deprecation notice originally appeared in OpenSSH 8.2: https://www.openssh.com/txt/release-8.2

It's been repeated in [8.3](https://www.openssh.com/txt/release-8.3) and [8.4](https://www.openssh.com/txt/release-8.4).

**Comment by thecliguy** [comment]
@jtesta Sorry to chase... I'm happy to submit a PR for this but wanted to check if you agree it's the right thing to do...? The last thing I want to do is make ssh-audit produce misleading information.

Do you have any plans for another ssh-audit release?

**Comment by jtesta** [comment]
> @jtesta Sorry to chase... I'm happy to submit a PR for this but
> wanted to check if you agree it's the right thing to do...? The last
> thing I want to do is make ssh-audit produce misleading information.

Sorry for the late reply.  I got side-tracked for a little while.

Sure, you can submit a PR for that.


> Do you have any plans for another ssh-audit release?

Perhaps once this issue and #90 are handled, it might make sense to
make one...

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by thecliguy** [comment]
@jtesta Are you happy with the following warning text: 
`A future deprecation notice has been issued in OpenSSH 8.2: https://www.openssh.com/txt/release-8.2`

So the output of `ssh-rsa` would be as follows:

```
(key) ssh-rsa -- [fail] using weak hashing algorithm
              `- [warn] A future deprecation notice has been issued in OpenSSH 8.2: https://www.openssh.com/txt/release-8.2
              `- [info] available since OpenSSH 2.5.0, Dropbear SSH 0.28
```

**Comment by jtesta** [comment]
On Sat, 2021-01-23 at 16:44 -0800, thecliguy wrote:
> @jtesta Are you happy with the following warning text:

Perhaps it should be an info-level message.  But otherwise, that sounds
good!

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by thecliguy** [comment]
PR submitted, see #92.

**Comment by thecliguy** [comment]
@jtesta Hi, I saw that you accepted the PR but it looks like the Travis build failed.... Did I do something wrong?

**Comment by jtesta** [comment]
I'm not sure if it failed because of your PR, or your PR+changes I added before merging.  Either way, it should be fixed now.  Thanks!
