### ISSUE TITLE
Add Sun_SSH support

### ISSUE THREAD

**Issue by brantleyp1** [jtesta/ssh-audit#9]
I assume this is the issue, but am using your script to test vulnerability fixes on some Solaris hosts and the ones with Openssh installed work correctly. On the hosts with sun_ssh I get:

```
ssh-audit.py solaristst2
Traceback (most recent call last):
  File "/usr/local/bin/ssh-audit.py", line 3016, in <module>
    audit(conf)
  File "/usr/local/bin/ssh-audit.py", line 3007, in audit
    SSH2.HostKeyTest.run(s, kex)
  File "/usr/local/bin/ssh-audit.py", line 625, in run
    SSH2.HostKeyTest.__test(s, server_kex, kex_str, kex_group, SSH2.HostKeyTest.HOST_KEY_TYPES)
  File "/usr/local/bin/ssh-audit.py", line 670, in __test
    host_key = kex_group.recv_reply(s, variable_key_len)
  File "/usr/local/bin/ssh-audit.py", line 2205, in recv_reply
    raise Exception('Expected MSG_KEXDH_REPLY (%d) or MSG_KEXDH_GEX_REPLY (%d), but got %d instead.' % (SSH.Protocol.MSG_KEXDH_REPLY, SSH.Protocol.MSG_KEXDH_GEX_REPLY, packet_type))
Exception: Expected MSG_KEXDH_REPLY (31) or MSG_KEXDH_GEX_REPLY (33), but got 4 instead.
```
Installed ssh is:
```
root@solaristst2:~# ssh -V
Sun_SSH_2.4, SSH protocols 1.5/2.0, OpenSSL 0x100020cf
```
System isn't fully updated but is fairly recent:
```
SunOS solaristst2 5.11 11.3 sun4v sparc sun4v
```

A system that returned usable info is set up as:
```
root@solarisprd2:# uname -a
SunOS solarisprd2 5.11 11.4.2.3.0 sun4v sparc sun4v
root@solarisprd2:# ssh -V
OpenSSH_7.5p1, OpenSSL 1.0.2p  14 Aug 2018
```

Let me know if there's any other data/info you need or how I could help.

**Comment by jtesta** [comment]
Thanks for the report!

> Let me know if there's any other data/info you need or how I could help.

I haven't installed Solaris in 15+ years, so I don't have any test machines, and I don't know the difficulty level at this point, either.  If you could perhaps temporarily make the SSH service available over the internet for me to test with, that would really speed things up.

If you can do this, please send me an email at jtesta -at-sign- positronsecurity -dot- com, and I'll send you my source IP so you can further restrict access.  Thanks!

**Comment by jtesta** [comment]
I got another idea: is the full server code publicly available?  If so, I could see about compiling it on Linux and testing it that way.

If that works, then I could integrate the process into the regular testing.  That would be ideal, as future updates would be guaranteed to maintain compatibility.

**Comment by jtesta** [comment]
@brantleyp1 Good news!  I was able to get access to a Sun_SSH server, debug the problem, and apply a fix to the `dev` branch.  Can you give it a try?

**Comment by brantleyp1** [comment]
Still error, but new error:
```
Traceback (most recent call last):
  File "./ssh-audit.py", line 3027, in <module>
    main()
  File "./ssh-audit.py", line 3024, in main
    audit(conf)
  File "./ssh-audit.py", line 3014, in audit
    SSH2.HostKeyTest.run(s, kex)
  File "./ssh-audit.py", line 627, in run
    SSH2.HostKeyTest.__test(s, server_kex, kex_str, kex_group, SSH2.HostKeyTest.HOST_KEY_TYPES)
  File "./ssh-audit.py", line 672, in __test
    host_key = kex_group.recv_reply(s, variable_key_len)
  File "./ssh-audit.py", line 2208, in recv_reply
    raise Exception('Expected MSG_KEXDH_REPLY (%d) or MSG_KEXDH_GEX_REPLY (%d), but got %d instead.' % (SSH.Protocol.MSG_KEXDH_REPLY, SSH.Protocol.MSG_KEXDH_GEX_REPLY, packet_type))
Exception: Expected MSG_KEXDH_REPLY (31) or MSG_KEXDH_GEX_REPLY (33), but got 4 instead.
```

Thank you for plugging away at this!

**Comment by brantleyp1** [comment]
Just for grins I checked on an older solaris system and the `dev` branch did work!

I got successful scan on:
```
brantley@workstation:ssh-audit-dev$ ./ssh-audit.py testsolwas1
# general
(gen) banner: SSH-2.0-Sun_SSH_1.1.6
(gen) compatibility: OpenSSH 3.9-6.6, Dropbear SSH 0.53+ (some functionality from 0.52)
(gen) compression: enabled (zlib)

# key exchange algorithms
...

~~~~~~~~~~~~~~~~~

brantley@testsolwas1:~# uname -a
SunOS testsolwas1 5.10 Generic_150400-13 sun4v sparc sun4v
brantley@testsolwas1:~# ssh -V
Sun_SSH_1.1.6, SSH protocols 1.5/2.0, OpenSSL 0x0090704f
```

**Comment by jtesta** [comment]
Well that's some good news.

Ok, try refreshing your `dev` branch.  I don't have a test machine to see if the newest fix is correct, but I made an educated guess.

**Comment by brantleyp1** [comment]
Very educated! That got it! 
```
brantley@workstation:ssh-audit-dev$ ./ssh-audit.py solaristst2
# general
(gen) banner: SSH-2.0-Sun_SSH_2.4
(gen) compatibility: OpenSSH 5.9-6.0, Dropbear SSH 2013.56+
(gen) compression: enabled (zlib@openssh.com, zlib)
```

Thank you so much!

**Comment by jtesta** [comment]
Great!  And you're welcome!

Since I just made a stable release not too long ago, and because I'd like to make more improvements first, I'm not planning on releasing another stable version for at least a couple more weeks.  But I always aim to keep the `dev` branch in good working order.  So you can keep using that in the meantime.

Please let me know if anything else goes wrong!
