### ISSUE TITLE
Microsoft Defender falsely identifies Windows beta build as malware

### ISSUE THREAD

**Issue by jtesta** [jtesta/ssh-audit#94]
When testing the Windows builds with the latest version of pyinstaller (4.2) and Python (3.9.1), Microsoft Defender claims ssh-audit.exe is "Trojan:Win32/Fuerboos.D!cl".  I've submitted this false positive to Microsoft, so hopefully it'll be resolved soon.

I suppose I'll hold the v2.4.0 release for a few days to see if they fix this issue.  Otherwise, perhaps I'll release 2.4.0 without a Windows build.

**Comment by jtesta** [comment]
After two rounds of speaking with Microsoft, it seems like this issue is now fixed... assuming users have updated AV definitions.

**Comment by michael-o** [comment]
Just happened here again with a colleague.

**Comment by jtesta** [comment]
Thanks for reporting this.

Sadly, there's nothing we can do about this.  Microsoft Defender is
being extremely lazy and flags a lot of legitimate Python code that's
compiled with PyInstaller.  Its likely that many other Python projects
are being flagged now as well.

I suppose the one thing you could do is report this false-positive to
Microsoft.  If enough people complain, they'll get nagged into fix it.
 Again.

**Comment by jbperrin88** [comment]
Hello there.

First of all , thanks for you work.

I need to tell you that microsoft is not the only one to see your exe as a malware.

trellix mcafee also tag you executable as a malware:
trojan: Artemis!B25D698FBB84

Best regards
