### ISSUE TITLE
Calling SSH_Socket 'Connect' Doesn't Return Errors After the First For Loop Iteration

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#97]
When auditing an SSH server, `audit` invokes:
https://github.com/jtesta/ssh-audit/blob/741bd631e24eec0e4965297dc78b9d7bb5b33e13/src/ssh_audit/ssh_audit.py#L824

The `connect` method contains a for loop:
https://github.com/jtesta/ssh-audit/blob/741bd631e24eec0e4965297dc78b9d7bb5b33e13/src/ssh_audit/ssh_socket.py#L154

The caller doesn't seem to return an error if it occurs **after the first iteration** of the loop.

This can be easily demonstrated by:
  * Placing a `sleep` within the connect method _(see sample code below)_.
  * Executing ssh-audit `(ssh-audit 127.0.0.1)`
  * Wait for first loop iteration to complete.
  * Stop the ssh daemon.

```python
    def connect(self) -> Optional[str]:
        '''Returns None on success, or an error string.'''
        
        ###########
        import time
        ###########
        
        err = None
        for af, addr in self._resolve():
            s = None
            try:
                
                ######################
                time.sleep(3)
                print('connecting...')
                ######################
                
                s = socket.socket(af, socket.SOCK_STREAM)
                s.settimeout(self.__timeout)
                s.connect(addr)
                self.__sock = s
                return None
            except socket.error as e:
                err = e
                self._close_socket(s)
        if err is None:
            errm = 'host {} has no DNS records'.format(self.__host)
        else:
            errt = (self.__host, self.__port, err)
            errm = 'cannot connect to {} port {}: {}'.format(*errt)
        
        #####################
        print('ERROR:', errm)
        #####################
        
        return '[exception] {}'.format(errm)
```

**Comment by thecliguy** [comment]
My analysis above is incorrect, so I'm closing this issue.

Errors returned by SSH_Socket's `connect` method are sometimes being suppressed because the caller doesn't return them. I will explain this more fully in a new issue.

**Comment by jtesta** [comment]
No problem.
