### ISSUE TITLE
SSH Connections - Additional Logging and Visibility of Errors

### ISSUE THREAD

**Issue by thecliguy** [jtesta/ssh-audit#98]
ADDITIONAL LOGGING
------------------

I'm planning on using `ssh-audit` in a production environment and would like to be able to demonstrate and record how _aggressive_ a typical audit is.

Currently verbose output only shows the initial SSH connection that's made to a target server:

  https://github.com/jtesta/ssh-audit/blob/c483fe1861bcfaefabec21a9195b7c226540aaa4/src/ssh_audit/ssh_audit.py#L823

However an audit actually makes multiple connections to a target server:

  1. The initial connection:       
       `ssh_audit.py`: `main` --> `audit` --> `err = s.connect()`
  
  2. Obtaining host key(s):        
       `ssh_audit.py`: `main` --> `audit` --> `HostKeyTest.run(s, kex)`
       `hostkeytest.py`: `run` --> `perform_test` --> `err = s.connect()`
       _(`err = s.connect()` runs once per key type [rsa, ed25519, etc])_
                                   
  3. Performing DH group exchange: 
       `ssh_audit.py`: `main` --> `audit` --> `GEXTest.run(s, kex)`
       `gextest.py`: `run` --> `GEXTest.reconnect`  --> `err = s.connect()`
       _(`GEXTest.reconnect` runs once per group-exchange alg and once per modulus length for each group-exchange alg)_

@jtesta Would you be happy to entertain the idea of adding some additional logging so that each SSH connection is output?
If that sounds OK, do you want this to be added to the existing verbose output or would it be more appropriate to add a new `--debug` parameter?

VISIBILITY OF ERRORS
--------------------

When obtaining host key(s) and performing DH group exchange, if `s.connect()` or `get_banner()` produce an error then currently the error message is suppressed:

  https://github.com/jtesta/ssh-audit/blob/c483fe1861bcfaefabec21a9195b7c226540aaa4/src/ssh_audit/hostkeytest.py#L109-L116

  https://github.com/jtesta/ssh-audit/blob/c483fe1861bcfaefabec21a9195b7c226540aaa4/src/ssh_audit/gextest.py#L45-L52

Should we at least display a warning rather than hiding errors?

**Comment by jtesta** [comment]
> @jtesta Would you be happy to entertain the idea of adding some
> additional logging so that each SSH connection is output?
> If that sounds OK, do you want this to be added to the existing
> verbose output or would it be more appropriate to add a new --debug
> parameter?

Yes, additional logging would be good.  And a new --debug parameter
would make sense in that case.


> Should we at least display a warning rather than hiding errors?

Yeah, they should be visible.  I'm leaning towards only printing them
when verbose or debug mode is enabled.

**Comment by thecliguy** [comment]
Thanks for the quick response.

Would you be able to show me the correct way to pass an instance of an `OutputBuffer` to `HostKeyTest.run()` and `GEXTest.run()`? Currently those classes don't produce any output.

Once I know how to do this correctly, I can work on implementing `--debug`.

**Comment by jtesta** [comment]
> Would you be able to show me the correct way to pass an instance of
> an OutputBuffer to HostKeyTest.run() and GEXTest.run()? Currently
> those classes don't produce any output.

Those methods are static, so you could simply pass in a reference to an
OutputBuffer.

**Comment by thecliguy** [comment]
Perfect, thank you.

**Comment by thecliguy** [comment]
@jtesta Should I bother annotating the argument that accepts an `OutputBuffer`?

EG:
```python
# gextest.py
def run(out: 'OutputBuffer', s: 'SSH_Socket', kex: 'SSH2_Kex') -> None:

# hostkeytest.py
def run(out: 'OutputBuffer', s: 'SSH_Socket', server_kex: 'SSH2_Kex') -> None:
```

In order for `tox` to parse the `'OutputBuffer'` annotation I'd have to import `OutputBuffer` in `gextest.py` and `hostkeytest.py`, EG:
```python
from ssh_audit.outputbuffer import OutputBuffer
```

**Comment by jtesta** [comment]
If tox complains about it, then yeah... we'd have to import it.

**Comment by jtesta** [comment]
Thanks for the PR!  I merged it and then made a small change: `SSH_Socket()` now takes an `OutputBuffer` so that all its methods can use it without having to pass it in every time.

> Is there any additional logging you want to add to Debug?

There's LOTS of debugging output we can potentially generate.  I figure we'll add it in as needed.  I'd be happy to accept debugging lines if you find them helpful.

Thanks again!
